import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const websiteRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(websiteRoot, "../..");
const manifestPath = resolve(repoRoot, "spec/v1_product_artifact_manifest.json");
const outputPath = resolve(websiteRoot, "src/v1/generated/abis.ts");
const check = process.argv.includes("--check");
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));

if (manifest.executionSpecId !== "V1-EXEC-11" || manifest.modules.length !== 19) {
  throw new Error("expected the frozen V1-EXEC-11 nineteen-module product manifest");
}

const artifactSources = [];
const moduleLines = [];
for (const module of [...manifest.modules].sort((a, b) => a.module.localeCompare(b.module))) {
  const artifactPath = resolve(repoRoot, module.interfaceArtifact);
  const artifactText = await readFile(artifactPath, "utf8");
  const artifact = JSON.parse(artifactText);
  if (!Array.isArray(artifact.abi)) throw new Error(`missing compiled ABI for ${module.module}`);
  const artifactSha256 = createHash("sha256").update(artifactText).digest("hex");
  artifactSources.push({ module: module.module, artifact: module.interfaceArtifact, artifactSha256 });
  moduleLines.push(`  ${JSON.stringify(module.module)}: ${JSON.stringify(artifact.abi)},`);
}

const fingerprint = createHash("sha256")
  .update(JSON.stringify({ executionSpecId: manifest.executionSpecId, artifactSources }))
  .digest("hex");
const output = `// Generated by scripts/generate-v1-abis.mjs from compiled E102 artifacts. Do not edit.\n\n`
  + `export const V1_EXECUTION_SPEC_ID = ${JSON.stringify(manifest.executionSpecId)} as const;\n`
  + `export const V1_ABI_FINGERPRINT = "sha256:${fingerprint}" as const;\n`
  + `export const V1_ABI_SOURCES = ${JSON.stringify(artifactSources, null, 2)} as const;\n\n`
  + `export const v1Abis = {\n${moduleLines.join("\n")}\n} as const;\n\n`
  + `export type V1ModuleName = keyof typeof v1Abis;\n`;

if (check) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== output) throw new Error("generated V1 ABI bridge is stale; run npm run generate:abis");
} else {
  await writeFile(outputPath, output);
}
