import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile, readdir, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const websiteRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(websiteRoot, "../..");
const manifestPath = resolve(repoRoot, "spec/v1_product_artifact_manifest.json");
const outputPath = resolve(websiteRoot, "src/v1/generated/abis.ts");
const currentOutputPath = resolve(websiteRoot, "src/v1/generated/current-abis.ts");
const burnOutputPath = resolve(websiteRoot, "src/v1/generated/burn-abis.ts");
const identityOutputPath = resolve(websiteRoot, "src/v1/generated/abi-identity.ts");
const legacyModulesOutputPath = resolve(websiteRoot, "src/v1/generated/legacy-contract-abis.ts");
const contractsRoot = resolve(websiteRoot, "src/v1/generated/contracts");
const check = process.argv.includes("--check");
const sourceOnly = process.argv.includes("--source-only");
if (sourceOnly && !check) throw new Error("source-only mode is verification only");
const manifestText = await readFile(manifestPath, "utf8");
const manifest = JSON.parse(manifestText);
const sha256 = value => createHash("sha256").update(value).digest("hex");
const inputsPath = resolve(websiteRoot, "build-inputs/v1-abis.json");
const inputIdentity = {
  schemaVersion: 1,
  executionSpecId: manifest.executionSpecId,
  manifestSha256: sha256(manifestText),
  interfaceSourceSha256: sha256(await readFile(resolve(repoRoot, "contracts/src/v1/interfaces/IV1Protocol.sol"))),
};
const savedInputs = check ? JSON.parse(await readFile(inputsPath, "utf8")) : null;
if (sourceOnly && Object.entries(inputIdentity).some(([key, value]) => savedInputs[key] !== value)) {
  throw new Error("ABI build input source identity is stale; regenerate from compiled artifacts");
}
const compiledInputs = [];
const legacySnapshot = await import(new URL("../src/v1/generated/legacy-abis.js", import.meta.url));

if (manifest.executionSpecId !== "V1-EXEC-11" || manifest.modules.length !== 18) {
  throw new Error("expected the current V1-EXEC-11 eighteen-module product manifest");
}

const artifactSources = [];
const currentValues = {};
const burnValues = {};
const burnShape = value => Array.isArray(value) ? value.filter(x => x?.name !== "lpFeePips" && x?.name !== "lpFeeMode").map(burnShape) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([k,v])=>[k,burnShape(v)])) : value;
for (const module of [...manifest.modules].sort((a, b) => a.module.localeCompare(b.module))) {
  const artifactPath = resolve(repoRoot, module.interfaceArtifact);
  const saved = sourceOnly ? savedInputs.modules[compiledInputs.length] : null;
  if (sourceOnly && (saved?.module !== module.module || saved?.artifact !== module.interfaceArtifact
    || !/^[0-9a-f]{64}$/.test(saved?.artifactSha256 ?? ""))) throw new Error("invalid ABI build input module identity");
  const artifactText = sourceOnly ? null : await readFile(artifactPath, "utf8");
  const artifact = sourceOnly ? saved : JSON.parse(artifactText);
  if (!Array.isArray(artifact.abi)) throw new Error(`missing compiled ABI for ${module.module}`);
  const artifactSha256 = sourceOnly ? saved.artifactSha256 : sha256(artifactText);
  compiledInputs.push({ module: module.module, artifact: module.interfaceArtifact, artifactSha256, abi: artifact.abi });
  artifactSources.push({ module: module.module, artifact: module.interfaceArtifact, artifactSha256 });
  currentValues[module.module] = artifact.abi;
  burnValues[module.module] = burnShape(artifact.abi);
}

const inputsText = JSON.stringify({ ...inputIdentity, modules: compiledInputs }, null, 2) + "\n";
if (check) {
  if (JSON.stringify(savedInputs) !== JSON.stringify(JSON.parse(inputsText))) throw new Error("ABI build inputs differ from compiled artifacts");
} else {
  await mkdir(dirname(inputsPath), { recursive: true });
  await writeFile(inputsPath, inputsText);
}

for (const module of manifest.extensionModules ?? []) {
  if (module.module !== "HolderRewardsDistributorV1") continue;
  currentValues[module.module] = module.abi;
  artifactSources.push({module: module.module, artifact: module.artifact, artifactSha256: createHash("sha256").update(JSON.stringify(module.abi)).digest("hex")});
}
const fingerprint = createHash("sha256")
  .update(JSON.stringify({ executionSpecId: manifest.executionSpecId, artifactSources }))
  .digest("hex");
const output = `// Generated by scripts/generate-v1-abis.mjs from compiled E102 artifacts. Do not edit.\n\n`
  + `export { V1_EXECUTION_SPEC_ID, V1_ABI_FINGERPRINT, V1_ABI_SOURCES } from "./abi-identity.ts";\n`
  + `export { currentV4Abis } from "./current-abis.ts";\n`
  + `export { burnV4Abis } from "./burn-abis.ts";\n`
  + `export { legacyV1Abis as v1Abis } from "./legacy-abis.ts";\nexport type V1ModuleName = keyof typeof import("./legacy-abis.ts").legacyV1Abis;\n`;
const identityOutput = `// Generated by scripts/generate-v1-abis.mjs from compiled E102 artifacts. Do not edit.\n\n`
  + `export const V1_EXECUTION_SPEC_ID = ${JSON.stringify(manifest.executionSpecId)} as const;\n`
  + `export const V1_ABI_FINGERPRINT = "sha256:${fingerprint}" as const;\n`
  + `export const V1_ABI_SOURCES = ${JSON.stringify(artifactSources, null, 2)} as const;\n`;
const currentNames = [...manifest.modules, ...(manifest.extensionModules ?? [])].map(x => x.module);
const burnNames = [...manifest.modules].map(x => x.module);
const legacyNames = Object.keys(legacySnapshot.legacyV1Abis);
const contractFiles = [];
for (const [version, names, values] of [["current", currentNames, currentValues], ["burn", burnNames, burnValues], ["legacy", legacyNames, legacySnapshot.legacyV1Abis]]) {
  for (const name of names) {
    contractFiles.push([resolve(contractsRoot, version, `${name}.ts`), `// Generated by scripts/generate-v1-abis.mjs. Do not edit.\n\nexport const ${name} = ${JSON.stringify(values[name])} as const;\nexport default ${name};\n`]);
  }
}
const currentImports = currentNames.map(name => `import ${name} from "./contracts/current/${name}.ts";`).join("\n");
const burnImports = burnNames.map(name => `import ${name} from "./contracts/burn/${name}.ts";`).join("\n");
const legacyImports = legacyNames.map(name => `import ${name} from "./contracts/legacy/${name}.ts";`).join("\n");
const currentOutputFinal = `// Generated by scripts/generate-v1-abis.mjs from compiled E102 artifacts. Do not edit.\n\n${currentImports}\n\nexport { ${currentNames.join(", ")} };\nexport const currentV4Abis = {\n${currentNames.map(name => `  ${JSON.stringify(name)}: ${name},`).join("\n")}\n} as const;\n`;
const burnOutputFinal = `// Generated by scripts/generate-v1-abis.mjs from compiled E102 artifacts. Do not edit.\n\n${burnImports}\n\nexport { ${burnNames.join(", ")} };\nexport const burnV4Abis = {\n${burnNames.map(name => `  ${JSON.stringify(name)}: ${name},`).join("\n")}\n} as const;\n`;
const legacyModulesOutputFinal = `// Generated by scripts/generate-v1-abis.mjs from the frozen legacy ABI snapshot. Do not edit.\n\n${legacyImports}\n\nexport { ${legacyNames.join(", ")} };\nexport const legacyV1Abis = {\n${legacyNames.map(name => `  ${JSON.stringify(name)}: ${name},`).join("\n")}\n} as const;\n`;

for (const [version, names] of [["current", currentNames], ["burn", burnNames], ["legacy", legacyNames]]) {
  const directory = resolve(contractsRoot, version);
  for (const file of await readdir(directory).catch(() => [])) {
    if (!names.some(name => file === `${name}.ts`)) {
      if (check) throw new Error(`obsolete contract ABI module: ${version}/${file}`);
      await rm(resolve(directory, file));
    }
  }
}

if (check) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== output) throw new Error("generated V1 ABI bridge is stale; run npm run generate:abis");
  for (const [path, expected, label] of [[identityOutputPath, identityOutput, "ABI identity"], [currentOutputPath, currentOutputFinal, "current ABI module"], [burnOutputPath, burnOutputFinal, "burn ABI module"], [legacyModulesOutputPath, legacyModulesOutputFinal, "legacy ABI module"], ...contractFiles.map(([path, expected]) => [path, expected, "contract ABI module"])] ) {
    const actual = await readFile(path, "utf8").catch(() => "");
    if (actual !== expected) throw new Error(`generated ${label} is stale; run npm run generate:abis`);
  }
} else {
  for (const [version, names] of [["current", currentNames], ["burn", burnNames], ["legacy", legacyNames]]) await mkdir(resolve(contractsRoot, version), { recursive: true });
  for (const [path, content] of contractFiles) await writeFile(path, content);
  await writeFile(identityOutputPath, identityOutput);
  await writeFile(currentOutputPath, currentOutputFinal);
  await writeFile(burnOutputPath, burnOutputFinal);
  await writeFile(legacyModulesOutputPath, legacyModulesOutputFinal);
  await writeFile(outputPath, output);
}
