import assert from 'node:assert/strict';import test from 'node:test';import ts from 'typescript';import {readFileSync} from 'node:fs';
import {buildCurveBuyRequest,buildCurveSellRequest,verifyCurveTradeResponse} from '../src/v1/features/launch.ts';
import {tradeContextKey} from '../src/v1/tradeContext.ts';import {tradeSubmissionError} from '../src/trade/submission-error.ts';
import {ROBINHOOD_CHAIN_ID} from '../src/v1/chain.ts';
const address=`0x${'1'.repeat(40)}`,pair=`0x${'2'.repeat(40)}`,hash=`0x${'3'.repeat(64)}`,zero=`0x${'0'.repeat(40)}`;
const display={sync:{chainId:ROBINHOOD_CHAIN_ID,status:'synced',finality:'head',blockNumber:'1',blockHash:hash,revision:`1:${hash}`},market:{marketId:hash,assetUid:hash,quoteAssetConfigId:hash,tickerGardenBaselineId:hash,curve:address,memeToken:address,quoteAsset:pair,launchPhase:0,sourceVersion:1,source:{chainId:ROBINHOOD_CHAIN_ID,blockNumber:'1',blockHash:hash,transactionHash:hash,transactionIndex:0,logIndex:0},canonicalRoute:{router:address,quoter:address,hook:address,launchLocker:address,graduationExecutor:address,sourceVersion:1,launchPhase:0,curveTradingEnabled:true},curveProgress:{realQuoteReserve:'1',sellableTokens:'1',reservedTokens:'1',accruedCurveFees:'0',readyToGraduate:false}}};
const tree=ts.createSourceFile('trade.ts',readFileSync(new URL('../src/controllers/trade.ts',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true);
function body(name:string){let source='';function walk(n:ts.Node){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)source=n.getText(tree);else ts.forEachChild(n,walk);}walk(tree);assert.ok(source);return ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;}
async function run(side:'buy'|'sell',conversion:boolean,failCanonical=false){
 const market=structuredClone(display),events:string[]=[],notices:string[]=[];let request:any;
 const quote={side,marketId:hash,input:6n,output:10n,minimum:9n,expiresAtMs:Date.now()+60000,revision:market.sync.revision,...(conversion?{conversion:{sellToken:zero,buyToken:pair,sellAmount:'6',minBuyAmount:'5'}}:{})};
 const input={value:'6',readOnly:false};
 const ctx:any={tradeSubmitting:false,foundation:{},wallet:{account:address},tradeMarket:market,tradeQuote:quote,tradeMarketVerified:true,tradeSide:side,tradeMetadata:{symbol:'SEED',quoteSymbol:'AAPL',quoteDecimals:18},query:()=>input,required:()=>input,verifyLiveWalletContext:async()=>{},confirmFlowAction:async()=>true,text:()=>{},notify:(m:string)=>notices.push(m),ensureCanonicalMarket:async()=>{events.push('canonical');if(failCanonical)throw Error('canonical mismatch');},publicClient:{getBalance:async()=>10n**18n,estimateFeesPerGas:async()=>({maxFeePerGas:1n}),estimateContractGas:async()=>{events.push('gas');return 100n;}},allowanceApproval:async()=>undefined};
 const vars={ctx,recovery:null,recoveryStorageUnavailable:false,tradeWalletRequested:false,renderPayments:()=>{},updateTradeAvailability:()=>{},quotedMinimum:(v:bigint)=>v,parseTokenAmount:(s:string)=>BigInt(s),payment:()=>({address:conversion?zero:pair,symbol:conversion?'ETH':'AAPL',decimals:18}),tradingRoute:()=>true,tradeContextKey,tradeConfirmationContent:()=>({}),formatUnits:(v:bigint)=>String(v),quoteIconUrl:()=>'',conversionFeeLabel:()=>'',TRADE_NATIVE:zero,ZERO_ADDRESS:zero,gasReserve:(g:bigint,p:bigint)=>g*p,verifyCurveTradeResponse,buildCurveBuyRequest,buildCurveSellRequest,canonicalAddress:(a:string)=>a,convertPayment:async()=>{events.push('conversion');return {...quote,conversion:undefined};},executeProjectTrade:async(v:any)=>{events.push('project');request=v.request;},completeTradeDisplay:()=>{},reportClientError:()=>{},tradeSubmissionError};
 const submit=new Function(...Object.keys(vars),body('tradeNetworkReserve')+body('submitTrade')+'return submitTrade;')(...Object.values(vars));await submit();return {events,notices,request};
}
for(const [side,conversion] of [['buy',true],['buy',false],['sell',false]] as const)test(`database head ${side}, conversion=${conversion} reaches request after live verification`,async()=>{
 const result=await run(side,conversion);assert.deepEqual(result.notices,[]);assert.equal(result.events[0],'canonical');assert.ok(result.events.includes('gas'));assert.equal(result.events.at(-1),'project');assert.equal(result.request.functionName,side);assert.equal(result.request.args[1],conversion?9n:10n);
});
test('canonical failure stops before ETH conversion or project wallet call',async()=>{const r=await run('buy',true,true);assert.deepEqual(r.events,['canonical']);assert.equal(r.request,undefined);assert.match(r.notices[0]??'',/not submitted/);});
