import { PAGE_PATHS, type PageName } from "./routes.ts";
export const SITE_ORIGIN="https://tickergarden.com";
export const THEME_COLOR="#f8f7f4";
type Metadata=Readonly<{title:string;description:string;url:string;canonical:string;robots:"index,follow"|"noindex,follow"}>;
const pages:Record<PageName,Pick<Metadata,"title"|"description">>={
 home:{title:"TickerGarden — Token Launches, Markets & Stock Staking",description:"Launch community tokens on Robinhood Chain, explore markets paired with 194 supported Stock Tokens, and stake eligible Stock Tokens to share base trading fees after Bloom."},
 markets:{title:"Explore Community Tokens & Markets — TickerGarden",description:"Browse community-launched tokens and markets on Robinhood Chain, and review market details before trading."},
 trade:{title:"Trade a market — TickerGarden",description:"View a token market on Robinhood Chain, check its current details, and review the available trading route."},
 create:{title:"Launch a Token on Robinhood Chain — TickerGarden",description:"Launch a community token on Robinhood Chain. Choose a paired asset, set LP fees, and configure staking rewards and optional token fee burning."},
 stats:{title:"Protocol Statistics & Market Activity — TickerGarden",description:"Review TickerGarden protocol statistics, market activity, and available historical data."},
 statsStocks:{title:"Stock Token Staking Statistics — TickerGarden",description:"View staking value by Stock Token and compare staking activity across supported assets on TickerGarden."},
 rewards:{title:"Rewards & Claims — TickerGarden",description:"Review available TickerGarden rewards and claims, including claim status and eligibility details."},
 staking:{title:"Stock Staking Rewards — TickerGarden",description:"Stake eligible stock tokens on TickerGarden to earn a share of 30% of base fees after Bloom. Review your position and available staking actions."},
 docs:{title:"TickerGarden Documentation — Markets, Tokens & Staking",description:"Learn how TickerGarden markets, Robinhood Chain token launches, stock staking, rewards, and protocol features work."},
 privacy:{title:"Privacy Policy — TickerGarden",description:"Read how TickerGarden handles information when you use the TickerGarden website and services."},
 terms:{title:"Terms of Use — TickerGarden",description:"Review the terms that apply to using the TickerGarden website and services."},
 "not-found":{title:"Page Not Found — TickerGarden",description:"The requested TickerGarden page could not be found. Explore community tokens, markets, and stock staking from the homepage."}
};
function cleanPath(path="/"){const pathname=path.startsWith("http")?new URL(path).pathname:(path.split(/[?#]/,1)[0]??"/");return pathname.replace(/\/+/g,"/").replace(/\/$/,"")||"/";}
export function pageMetadata(page:PageName,path?:string,indexable=true):Metadata{const pathname=cleanPath(path??(page==="not-found"?"/404":PAGE_PATHS[page]));const id=page==="trade"?new URL(path??"/trade",SITE_ORIGIN).searchParams.get("marketId"):null;const canonical=`${SITE_ORIGIN}${pathname}${id&&/^0x[0-9a-f]{64}$/i.test(id)?`?marketId=${id.toLowerCase()}`:""}`;return {...pages[page],url:canonical,canonical,robots:!indexable||page==="not-found"?"noindex,follow":"index,follow"};}
function setMeta(name:string,content:string,attribute="name"){const selector=`meta[${attribute}="${name}"]`;let element=document.head.querySelector<HTMLMetaElement>(selector);if(!element){element=document.createElement("meta");element.setAttribute(attribute,name);document.head.append(element);}element.content=content;}
export function applyPageMetadata(page:PageName,title?:string,path?:string){const metadata=pageMetadata(page,path??window.location.pathname+window.location.search,document.documentElement.dataset.searchIndex==="allow"&&window.location.hostname==="tickergarden.com");document.title=title??metadata.title;setMeta("description",metadata.description);setMeta("robots",metadata.robots);setMeta("theme-color",THEME_COLOR);setMeta("og:title",document.title,"property");setMeta("og:description",metadata.description,"property");setMeta("og:site_name","TickerGarden","property");setMeta("og:url",metadata.url,"property");setMeta("og:type","website","property");setMeta("og:image",`${SITE_ORIGIN}/share.png`,"property");setMeta("twitter:image",`${SITE_ORIGIN}/share.png`);setMeta("twitter:card","summary");setMeta("twitter:title",document.title);setMeta("twitter:description",metadata.description);let link=document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement("link");link.rel="canonical";document.head.append(link);}link.href=metadata.canonical;}
export function renderMetadata(page:PageName,path?:string,indexable=true){const metadata=pageMetadata(page,path,indexable);const esc=(value:string)=>value.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return `<title>${esc(metadata.title)}</title><meta name="description" content="${esc(metadata.description)}"><meta name="robots" content="${metadata.robots}"><meta name="theme-color" content="${THEME_COLOR}"><link rel="canonical" href="${esc(metadata.canonical)}"><meta property="og:title" content="${esc(metadata.title)}"><meta property="og:description" content="${esc(metadata.description)}"><meta property="og:site_name" content="TickerGarden"><meta property="og:url" content="${esc(metadata.url)}"><meta property="og:type" content="website"><meta property="og:image" content="${SITE_ORIGIN}/share.png"><meta name="twitter:image" content="${SITE_ORIGIN}/share.png"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(metadata.title)}"><meta name="twitter:description" content="${esc(metadata.description)}">`;}
