#!/usr/bin/env python3
"""Generate Go DTOs and the embedded contract from the canonical OpenAPI."""
import argparse
import difflib
import json
from pathlib import Path
import subprocess

NAMES = ['SourceBlock', 'SyncStatus', 'PoolKeyReadModel', 'CanonicalRoute', 'CurveProgress',
         'MarketIdentityReadModel', 'MarketMetricsReadModel', 'MarketReadModel', 'ConfigReadModel', 'QuoteClaimable', 'MemeClaimable', 'UserPositionReadModel', 'UserAccountReadModel']
ACRONYMS = {'id':'ID', 'chainId':'ChainID', 'marketId':'MarketID', 'assetUid':'AssetUID', 'poolId':'PoolID',
            'quoteAssetConfigId':'QuoteAssetConfigID', 'tickerGardenBaselineId':'TickerGardenBaselineID',
            'volume24hUsd':'Volume24hUSD', 'marketCapUsd':'MarketCapUSD', 'quoteUsdMidpoint':'QuoteUSDMidpoint',
            'usdPriceAsOf':'USDPriceAsOf', 'usdPriceSource':'USDPriceSource'}


def go_type(shape, field):
    if '$ref' in shape:
        name = shape['$ref'].removeprefix('#/components/schemas/')
        if name not in NAMES:
            raise ValueError(f'unsupported reference {name}')
        return name
    if 'oneOf' in shape:
        variants = shape['oneOf']
        values = [v for v in variants if v.get('type') != 'null']
        if len(values) != 1 or len(variants) != 2:
            raise ValueError(f'unsupported union {field}')
        return '*' + go_type(values[0], field)
    typ = shape.get('type')
    if typ == 'string': return 'string'
    if typ == 'boolean': return 'bool'
    if typ == 'integer': return 'int64' if field == 'tickSpacing' else 'uint64'
    if typ == 'object' and field == 'values':
        expected = {'oneOf': [{'type': t} for t in ['string', 'number', 'boolean', 'null']]}
        if shape.get('additionalProperties') != expected:
            raise ValueError('unsupported config values type')
        return 'map[string]any'
    if typ == 'array' and field == 'claimable':
        expected = [{'$ref': '#/components/schemas/' + t} for t in ['QuoteClaimable', 'MemeClaimable']]
        if shape.get('prefixItems') != expected or shape.get('minItems') != 2 or shape.get('maxItems') != 2:
            raise ValueError('unsupported claimable tuple')
        return '[]Claimable'
    raise ValueError(f'unsupported shape for {field}: {shape}')


def render(document):
    blocks = ['// Code generated by scripts/generate_models.py from services/backend-go/openapi/v1.json; DO NOT EDIT.\npackage readmodel\nimport "encoding/json"\n']
    for name in NAMES:
        schema = document['components']['schemas'][name]
        props = schema['properties']
        optional = set(props) - set(schema['required'])
        if optional and not (name == 'MarketReadModel' and optional == {'identity', 'metrics'}):
            raise ValueError(f'optional field representation must be reviewed: {name}')
        fields = []
        for k,v in props.items():
            typ = go_type(v,k)
            if k in optional: typ = '*' + typ
            tag = k + (',omitempty' if k in optional else '')
            fields.append(f'{ACRONYMS.get(k, k[0].upper()+k[1:])} {typ} `json:"{tag}"`')
        blocks.append('type ' + name + ' struct {\n' + '\n'.join(fields) + '\n}\n')
    blocks.append('''type Claimable struct {Kind string `json:"kind"`; Asset string `json:"asset"`; Amount string `json:"amount"`}
    type Snapshot struct {
    ExecutionSpecID string `json:"executionSpecId"`
    ReconciliationAlerts []json.RawMessage `json:"reconciliationAlerts"`
    Sync SyncStatus `json:"sync"`
    Markets []MarketReadModel `json:"markets"`
    Configs []ConfigReadModel `json:"configs"`
    Accounts *[]UserAccountReadModel `json:"accounts,omitempty"`
    Positions []UserPositionReadModel `json:"positions"`
    }''')
    return subprocess.run(['gofmt'], input='\n'.join(blocks), text=True, capture_output=True, check=True).stdout


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[3]
    spec = root / 'services/backend-go/openapi/v1.json'
    target = root / 'services/backend-go/internal/readmodel/models.go'
    embedded = target.with_name('openapi.json')
    generated = render(json.loads(spec.read_text()))
    if args.check:
        if target.read_text() != generated or embedded.read_bytes() != spec.read_bytes():
            print(''.join(difflib.unified_diff(target.read_text().splitlines(True), generated.splitlines(True))))
            raise SystemExit('generated Go models or embedded OpenAPI are stale')
    else:
        target.write_text(generated)
        embedded.write_bytes(spec.read_bytes())


if __name__ == '__main__':
    main()
