import {chromium}from'../../apps/web/node_modules/playwright-core/index.mjs';import{readFileSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';const dir=new URL(process.env.TG_CAPACITY_EVIDENCE_DIR??'../../docs/reviews/evidence/full-local-integration-2026-09-13/',import.meta.url),meta=JSON.parse(readFileSync(new URL(process.env.TG_CAPACITY_API_META??'local-api.json',dir))),origin='http://127.0.0.1:18771',report={scope:'real browser UI interactions with local API; no wallet transaction approvals',checks:[]};const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
async function check(name,mobile,fn){const start=Date.now();try{const detail=await fn();report.checks.push({name,mobile,pass:true,elapsedMs:Date.now()-start,detail})}catch(e){report.checks.push({name,mobile,pass:false,elapsedMs:Date.now()-start,error:e.message})}}
try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile});await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const page=await context.newPage();await page.goto(origin+'/explore',{waitUntil:'domcontentloaded',timeout:60000});const first=page.locator('[data-stage-grid="0"] [data-runtime-market]').first();await first.waitFor({timeout:20000});await page.locator('[data-stage-next="0"]:not([disabled])').waitFor({timeout:20000});
 await check('next page completes and preserves other stage',mobile,async()=>{const before=await first.getAttribute('data-runtime-market'),other=await page.locator('[data-stage-grid="1"]').innerText();await page.locator('[data-stage-next="0"]').click();await page.waitForFunction(before=>document.querySelector('[data-stage-grid="0"] [data-runtime-market]')?.getAttribute('data-runtime-market')!==before,before,{timeout:15000});assert.equal(await page.locator('[data-stage-grid="1"]').innerText(),other);return{before,after:await first.getAttribute('data-runtime-market')}});
 await check('search identifies exact synthetic market',mobile,async()=>{await page.locator('[data-market-search]').fill('Local Market 00099');await page.waitForFunction(()=>{const cards=[...document.querySelectorAll('[data-runtime-market]')];return cards.length===1&&cards[0].textContent.includes('Local Market 00099')},null,{timeout:20000})});
 await check('search error is visible and recovers',mobile,async()=>{await page.route('**/v1/markets?**',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'local_injected_failure',message:'Local failure injection'})}));await page.locator('[data-market-search]').fill('Local Market 00098');await page.waitForFunction(()=>document.body.innerText.includes('couldn’t load')||document.body.innerText.includes('could not be verified'),null,{timeout:15000});await page.unroute('**/v1/markets?**');await page.locator('[data-market-search]').fill('Local Market 00097');await page.waitForFunction(()=>[...document.querySelectorAll('[data-runtime-market]')].some(x=>x.textContent.includes('Local Market 00097')),null,{timeout:15000})});
 await page.goto(origin+'/trade?marketId='+meta.marketId,{waitUntil:'domcontentloaded',timeout:60000});await page.locator('[data-detail-symbol]').first().waitFor();await page.waitForFunction(()=>document.querySelector('[data-detail-source]')?.textContent?.includes('Updated'),null,{timeout:20000});await page.waitForLoadState('networkidle',{timeout:20000});let calls=[];page.on('request',r=>{if(r.url().startsWith(meta.origin))calls.push(new URL(r.url()).pathname)});
 await check('rapid chart changes retain trade input and final selection',mobile,async()=>{await page.locator('[data-trade-amount]').fill('0.123');calls=[];const firstChart=page.waitForRequest(r=>r.url().startsWith(meta.origin)&&new URL(r.url()).pathname.endsWith('/candles'),{timeout:15000});await page.locator('[data-detail-period="12H"]').click();await firstChart;await page.locator('[data-detail-period="1D"]').click();await page.waitForTimeout(1800);assert.equal(await page.locator('[data-detail-period="1D"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-trade-amount]').inputValue(),'0.123');assert.ok(calls.some(x=>x.endsWith('/candles')));assert.ok(!calls.some(x=>x.includes('/config/')||x==='/v1/markets'||x==='/v1/protocol-statistics'),JSON.stringify(calls));return{requests:calls}});
 await context.close()}}catch(e){report.fatal=e.stack}finally{await browser.close();report.status=report.fatal||report.checks.some(x=>!x.pass)?'issues_found':'passed';if(report.status!=='passed')process.exitCode=1;writeFileSync(new URL('browser-flows.json',dir),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report))}
