// Append a NEW synthetic publication so browser freshness checks are meaningful.
// Existing immutable publication records remain untouched. No RPC / real chain is involved.
import {createRequire} from 'node:module';import{readFileSync,writeFileSync}from'node:fs';const require=createRequire(new URL('../../services/backend-ts/package.json',import.meta.url)),{Pool}=require('pg');const dir=new URL('../../docs/reviews/evidence/full-local-integration-2026-09-13/',import.meta.url),meta=JSON.parse(readFileSync(new URL('local-api.json',dir)));if(!/^tg_full_scale_\d+$/.test(meta.schemaName))throw Error('local test only');const s='"'+meta.schemaName+'"',p=new Pool({connectionString:'postgres://tickergarden:tickergarden_dev@127.0.0.1:54329/tickergarden',max:1});
try{const oldRevision=meta.revision,number=Number(oldRevision.split(':')[0])+1,hash='0x'+BigInt(900000+number-4).toString(16).padStart(64,'0'),revision=number+':'+hash,now=Math.floor(Date.now()/60000)*60;await p.query('BEGIN');
 await p.query(`INSERT INTO ${s}.chain_blocks(environment,chain_id,deployment_digest,number,hash,parent_hash,canonical,finalized,source_timestamp) SELECT environment,chain_id,deployment_digest,$1,$2,hash,true,true,to_timestamp($3) FROM ${s}.chain_blocks WHERE number=$4`,[number,hash,now,number-1]);
 await p.query(`INSERT INTO ${s}.publications(environment,chain_id,deployment_digest,scope,revision,block_number,block_hash,generation,payload_digest,payload) SELECT environment,chain_id,deployment_digest,scope,$1,$2,$3,generation,payload_digest,payload FROM ${s}.publications WHERE revision=$4 AND scope IN ('markets','configs','positions','accounts')`,[revision,number,hash,oldRevision]);
 await p.query(`INSERT INTO ${s}.projection_records(environment,chain_id,deployment_digest,scope,revision,identity,sort_key,payload_digest,payload) SELECT environment,chain_id,deployment_digest,scope,$1,identity,sort_key,payload_digest,CASE WHEN scope='markets' THEN jsonb_set(jsonb_set(jsonb_set(payload,'{display,asOfTimestamp}',to_jsonb($2::text)),'{display,blockNumber}',to_jsonb($3::text)),'{display,blockHash}',to_jsonb($4::text)) ELSE payload END FROM ${s}.projection_records WHERE revision=$5 AND scope IN ('markets','configs','positions','accounts')`,[revision,String(now),String(number),hash,oldRevision]);
 await p.query(`UPDATE ${s}.publication_pointers SET revision=$1 WHERE scope IN ('markets','configs','positions','accounts')`,[revision]);await p.query(`UPDATE ${s}.covered_ranges SET to_block=$1`,[number]);await p.query(`UPDATE ${s}.ingestion_checkpoints SET next_block=$1,last_block_hash=$2`,[number+1,hash]);await p.query(`UPDATE ${s}.projection_checkpoints SET next_block=$1,last_revision=$2 WHERE scope='analytics'`,[number+1,revision]);await p.query(`UPDATE ${s}.holder_snapshots SET block_number=$1,block_hash=$2`,[number,hash]);await p.query(`UPDATE ${s}.holder_balances SET block_hash=$1`,[hash]);await p.query('COMMIT');
 meta.revision=revision;writeFileSync(new URL('local-api.json',dir),JSON.stringify(meta));writeFileSync(new URL('fixture-clock.json',dir),JSON.stringify({scope:'new synthetic publication only; prior immutable records preserved',oldRevision,revision,now}));
}catch(e){await p.query('ROLLBACK');throw e}finally{await p.end()}
