// Actual relay process against local WSS/RPC/queue and isolated PostgreSQL schema.
import {createRequire} from 'node:module';
import {spawn,execFileSync} from 'node:child_process';
import {createServer as httpsServer} from 'node:https';
import {createServer as httpServer} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {performance} from 'node:perf_hooks';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../services/backend-ts/package.json',import.meta.url));
const {Pool}=require('pg'),{WebSocketServer}=require('ws');
const node='/Users/dear/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node';
const schema=`tg_relay_load_${process.pid}`,base='postgres://tickergarden:tickergarden_dev@127.0.0.1:54329/tickergarden';
const db=base+'?options='+encodeURIComponent('-csearch_path='+schema),admin=new Pool({connectionString:base}),pool=new Pool({connectionString:db});
const filter=JSON.parse(readFileSync(new URL('../../infra/vps/chain-event-relay/filter.json',import.meta.url)));
const evidence=new URL(process.env.TG_CAPACITY_EVIDENCE_DIR ?? '../../docs/reviews/evidence/full-local-integration-2026-09-13/',import.meta.url);
const h=n=>'0x'+BigInt(n).toString(16).padStart(64,'0'),hex=n=>'0x'+BigInt(n).toString(16);
const report={scope:'real relay process and PostgreSQL; local fake WSS provider and queue; 21500 synthetic markets',runtime:process.version,subscriptions:[],runs:[],checks:[]};
const temp=mkdtempSync(tmpdir()+'/tg-relay-');let child,wss,wsServer,rpcServer,queueServer,currentSocket,stderr='',subCounter=0,head=Number(filter.activationBlock)+1,queueDelay=0,queueFailure=false,queueBlock=false,attempted=[],received=[],backfillLogs=[],rpcCalls=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,timeout=30000){const t=Date.now();while(Date.now()-t<timeout){if(await fn())return;await sleep(50)}throw Error('local test condition timed out')}
const listen=(s,p)=>new Promise(r=>s.listen(p,'127.0.0.1',r));
async function counts(){return (await pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE state='queued')::int queued,count(*) FILTER(WHERE state IN ('pending','leased'))::int pending,count(*) FILTER(WHERE state='dead')::int dead FROM chain_relay_events")).rows[0]}
function log(n,removed=false){return{address:filter.fixedAddresses.find(x=>x!==filter.sharedPoolManager.address),blockNumber:hex(head),blockHash:h(head),transactionHash:h(100000+n),transactionIndex:'0x0',logIndex:'0x0',topics:[filter.eventTopics.find(x=>x!==filter.sharedPoolManager.swapTopic)],data:'0x',removed}}
function emit(item){assert.ok(currentSocket&&currentSocket.readyState===1);currentSocket.send(JSON.stringify({jsonrpc:'2.0',method:'eth_subscription',params:{subscription:'0x1',result:item}}))}
try{
 await admin.query(`CREATE SCHEMA ${schema}`);
 await pool.query('CREATE TABLE contract_sources(environment text,chain_id bigint,deployment_digest text,module text,address text,birth_block bigint,runtime_code_hash text,active boolean);CREATE TABLE projection_records(environment text,chain_id bigint,deployment_digest text,scope text,revision text,payload jsonb);CREATE VIEW projection_read_records AS SELECT * FROM projection_records;CREATE TABLE publication_pointers(environment text,chain_id bigint,deployment_digest text,scope text,revision text)');
 await pool.query("INSERT INTO contract_sources SELECT 'test',$1,$2,'load','0x'||lpad(to_hex(g+100000),40,'0'),$3,$4,true FROM generate_series(1,43000) g",[filter.chainId,filter.releaseId,filter.activationBlock,h(1)]);
 await pool.query("INSERT INTO publication_pointers VALUES('test',$1,$2,'markets','load')",[filter.chainId,filter.releaseId]);
 await pool.query("INSERT INTO projection_records SELECT 'test',$1,$2,'markets','load',jsonb_build_object('poolId','0x'||lpad(to_hex(g),64,'0'),'source',jsonb_build_object('blockNumber',$3::text)) FROM generate_series(1,1500) g",[filter.chainId,filter.releaseId,filter.activationBlock]);
 execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',temp+'/key','-out',temp+'/crt','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost,IP:127.0.0.1','-days','1'],{stdio:'ignore'});
 wsServer=httpsServer({key:readFileSync(temp+'/key'),cert:readFileSync(temp+'/crt')});wss=new WebSocketServer({server:wsServer});
 wss.on('connection',socket=>{currentSocket=socket;socket.on('message',raw=>{const m=JSON.parse(String(raw));let result;if(m.method==='eth_subscribe'){result=hex(++subCounter);report.subscriptions.push({bytes:raw.length,addresses:Array.isArray(m.params[1].address)?m.params[1].address.length:1,poolTopics:m.params[1].topics?.[1]?.length??0})}else if(m.method==='eth_unsubscribe')result=true;else if(m.method==='eth_blockNumber')result=hex(head);else if(m.method==='eth_getBlockByNumber')result={number:hex(head),hash:h(head)};else throw Error('unexpected WS method');socket.send(JSON.stringify({jsonrpc:'2.0',id:m.id,result}))})});await listen(wsServer,18781);
 rpcServer=httpServer(async(req,res)=>{let b='';for await(const c of req)b+=c;const m=JSON.parse(b);rpcCalls.push({method:m.method,params:m.params});const result=m.method==='eth_blockNumber'?hex(head):m.method==='eth_getBlockByNumber'?{number:hex(head),hash:h(head)}:m.method==='eth_getLogs'?backfillLogs.filter(l=>BigInt(l.blockNumber)>=BigInt(m.params[0].fromBlock)&&BigInt(l.blockNumber)<=BigInt(m.params[0].toBlock)&&((Array.isArray(m.params[0].address)?m.params[0].address:[m.params[0].address]).includes(l.address))):null;res.setHeader('content-type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result}))});await listen(rpcServer,18782);
 queueServer=httpServer(async(req,res)=>{let b='';for await(const c of req)b+=c;attempted.push({dedup:req.headers['upstash-deduplication-id'],body:JSON.parse(b)});await sleep(queueDelay);if(queueFailure||queueBlock){queueFailure=false;res.writeHead(503).end('{}');return}received.push({at:performance.now(),body:JSON.parse(b),dedup:req.headers['upstash-deduplication-id']});res.writeHead(200,{'content-type':'application/json'}).end('{}')});await listen(queueServer,18783);
 const env={PGAPPNAME:schema,PATH:process.env.PATH,HOME:process.env.HOME,NODE_EXTRA_CA_CERTS:temp+'/crt',TG_ENVIRONMENT:'test',TG_DATABASE_SCHEMA:schema,CHAIN_RELAY_WS_URL:'wss://127.0.0.1:18781',CHAIN_RELAY_HTTP_URL:'http://127.0.0.1:18782',CHAIN_RELAY_DATABASE_URL:db,CHAIN_SOURCE_DATABASE_URL:db,CHAIN_RELAY_QUEUE_URL:'http://127.0.0.1:18783',CHAIN_RELAY_DESTINATION:'https://local.invalid/v1/webhooks/chain-relay',QUEUE_PUBLISH_TOKEN:'local-test-only',PORT:'18784',CHAIN_RELAY_MAX_BACKFILL_BLOCKS:'10000',CHAIN_RELAY_SOURCE_REFRESH_MS:'5000'};
 child=spawn(node,['--experimental-strip-types','infra/vps/chain-event-relay/src/server.ts'],{env,stdio:['ignore','pipe','pipe']});child.stderr.on('data',d=>stderr+=String(d));
 await until(async()=>{const r=await fetch('http://127.0.0.1:18784/healthz').catch(()=>null);if(r?.status===200){report.initialHealth=await r.json();return true}return false});assert.equal(report.initialHealth.activePools,1500);assert.ok(report.initialHealth.activeSources>=43000);
 if(process.argv.includes('--burst-only')){queueDelay=50;report.steady=[];const start=performance.now();for(let second=0;second<10;second++){for(let i=0;i<100;i++)emit(log(3000000+second*100+i));await sleep(1000);report.steady.push({second:second+1,elapsedMs:performance.now()-start,...await counts()})}report.atEndOfInput=await counts();await until(async()=>(await counts()).queued===1000,30000);report.drainMs=performance.now()-start-10000;report.finalCounts=await counts();report.checks.push({name:'100 events per second for 10 seconds drain without loss or dead events',pass:report.finalCounts.total===1000&&report.finalCounts.queued===1000&&report.finalCounts.dead===0});report.status=report.checks.every(x=>x.pass)?'passed':'failed';}else{
 for(const delay of (process.argv.includes("--recovery-only")?[]:[0,50,200])){queueDelay=delay;const before=await counts(),r0=received.length,t=performance.now();for(let i=1;i<=100;i++)emit(log(delay*1000+i));await until(async()=>(await counts()).total===before.total+100);const persistedMs=performance.now()-t;await sleep(1000);const afterOneSecond=await counts();await until(async()=>(await counts()).queued===before.queued+100,45000);const elapsed=performance.now()-t;report.runs.push({queueRttMs:delay,events:100,persistedMs,afterOneSecond,totalMs:elapsed,queuedPerSecond:100000/elapsed,actualQueueDeliveries:received.length-r0});console.log('relay RTT',delay,'done')}
 const previous=await counts(),n=765432;emit(log(n));emit(log(n));emit(log(n,true));await until(async()=>(await counts()).queued===previous.queued+2);report.checks.push({name:'duplicate canonical log deduplicated, removed log independently queued',pass:(await counts()).total===previous.total+2});
 queueDelay=0;queueFailure=true;const before=await counts();emit(log(777777));await until(async()=>(await counts()).queued===before.queued+1);const retry=await pool.query('SELECT max(attempt)::int attempts FROM chain_relay_events');report.checks.push({name:'queue 503 retries from durable inbox',pass:retry.rows[0].attempts>=2,attempts:retry.rows[0].attempts});
 const backfillBefore=await counts();head++;backfillLogs=[log(888888)];currentSocket.terminate();await until(async()=>(await counts()).queued===backfillBefore.queued+1,60000);report.checks.push({name:'disconnect and missed-block HTTP backfill',pass:rpcCalls.some(x=>x.method==='eth_getLogs')});
 const refreshStart=performance.now(),beforeSubs=report.subscriptions.length;await pool.query("INSERT INTO contract_sources VALUES('test',$1,$2,'load',$3,$4,$5,true)",[filter.chainId,filter.releaseId,'0x'+(999999).toString(16).padStart(40,'0'),head,h(1)]);await until(()=>report.subscriptions.length>beforeSubs,90000);await until(async()=>{const r=await fetch('http://127.0.0.1:18784/healthz').then(r=>r.json());return r.ok&&r.activeSources===report.initialHealth.activeSources+1},90000);report.routingRefreshMs=performance.now()-refreshStart;
 const sameBlockBefore=await counts(),subsBefore=report.subscriptions.length,getsBefore=rpcCalls.filter(x=>x.method==='eth_getLogs').length;
 backfillLogs=[log(999123)];currentSocket.terminate();await until(()=>report.subscriptions.length>subsBefore,60000);await sleep(1500);const sameBlockAfter=await counts();report.checks.push({name:'same-block disconnect gap is replayed',pass:received.some(x=>x.body.log.transactionHash===log(999123).transactionHash),expectedAdditionalLogs:1,actualAdditionalLogs:sameBlockAfter.total-sameBlockBefore.total,newGetLogsCalls:rpcCalls.filter(x=>x.method==='eth_getLogs').length-getsBefore});
 const ownIdle=(await admin.query("SELECT pid FROM pg_stat_activity WHERE application_name=$1 AND state='idle' LIMIT 1",[schema])).rows[0];assert.ok(ownIdle,'owned idle connection exists');
 await admin.query('SELECT pg_terminate_backend($1)',[ownIdle.pid]);await sleep(300);const recoveryBefore=await counts();emit(log(999888));await until(async()=>(await counts()).queued===recoveryBefore.queued+1,45000);
 report.checks.push({name:'relay survives an owned database connection termination and continues durable delivery',pass:child.exitCode===null});
 const restartBefore=await counts();queueBlock=true;const restartLog=log(999889);emit(restartLog);
 await until(async()=>Number((await pool.query("SELECT count(*) n FROM chain_relay_batches WHERE state='pending' AND last_error IS NOT NULL")).rows[0].n)>0);
 const sealed=(await pool.query("SELECT batch_key FROM chain_relay_events WHERE payload::jsonb->'log'->>'transactionHash'=$1",[restartLog.transactionHash])).rows[0].batch_key;
 child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));queueBlock=false;
 child=spawn(node,['--experimental-strip-types','infra/vps/chain-event-relay/src/server.ts'],{env,stdio:['ignore','pipe','pipe']});child.stderr.on('data',d=>stderr+=String(d));
 await until(async()=>(await counts()).queued===restartBefore.queued+1,45000);
 const attempts=attempted.filter(x=>x.body.log.transactionHash===restartLog.transactionHash);
 assert.ok(attempts.length>=2);assert.equal(new Set(attempts.map(x=>x.dedup)).size,1);assert.equal(attempts[0].dedup,'tg-chain-relay-'+sealed);
 report.checks.push({name:'process restart retries sealed durable batch using identical idempotency key',pass:true,attempts:attempts.length});
 report.batchCounts=(await pool.query("SELECT count(*)::int batches,sum(event_count)::int rawEvents FROM chain_relay_batches WHERE state='queued'")).rows[0];
 report.finalHealth=await(await fetch('http://127.0.0.1:18784/healthz')).json();report.finalCounts=await counts();report.httpBackfillCalls=rpcCalls.filter(x=>x.method==='eth_getLogs').length;report.status=report.checks.every(x=>x.pass)?'passed':'failed';}
}catch(e){report.status='failed';report.error=e.stack;report.childExit=child?.exitCode;report.rpcCalls=rpcCalls;report.finalCounts=await counts().catch(()=>null);report.finalHealth=await fetch('http://127.0.0.1:18784/healthz').then(r=>r.json()).catch(()=>null);console.error(e.message);process.exitCode=1}
finally{if(child){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),sleep(1500)]);if(child.exitCode===null)child.kill('SIGKILL')}if(wss){for(const c of wss.clients)c.terminate();wss.close()}for(const s of [wsServer,rpcServer,queueServer])if(s){s.closeAllConnections?.();await new Promise(r=>s.close(r))}await pool.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();rmSync(temp,{recursive:true,force:true});report.stderr=stderr;writeFileSync(new URL(process.argv.includes('--burst-only')?'relay-burst.json':process.argv.includes('--recovery-only')?'relay-recovery.json':'relay-load.json',evidence),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,runs:report.runs,checks:report.checks,error:report.error}))}
