package holderledger

import (
	"bufio"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"
)

// This opt-in fixture is generated by the real Solidity distributor, not by the
// Go model. Run scripts/verify_holder_ledger_solidity.py to regenerate and check.
func TestSolidityConformance(t *testing.T) {
	path := os.Getenv("TG_HOLDER_SOLIDITY_LOG")
	if path == "" {
		t.Skip("run scripts/verify_holder_ledger_solidity.py")
	}
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	scan := bufio.NewScanner(f)
	scan.Buffer(make([]byte, 4096), 1<<20)
	var ledger *Ledger
	var registration map[string]json.RawMessage
	var action *Action
	steps := 0
	text := func(m map[string]json.RawMessage, key string) string {
		t.Helper()
		b, ok := m[key]
		if !ok {
			t.Fatalf("missing Solidity field %s", key)
		}
		if len(b) > 0 && b[0] == '"' {
			var s string
			if json.Unmarshal(b, &s) != nil {
				t.Fatal("bad Solidity field", key)
			}
			return strings.ToLower(s)
		}
		return string(b)
	}
	number := func(m map[string]json.RawMessage, key string) uint64 {
		t.Helper()
		n, e := strconv.ParseUint(text(m, key), 10, 64)
		if e != nil {
			t.Fatal(e)
		}
		return n
	}
	for scan.Scan() {
		line := strings.TrimSpace(scan.Text())
		if !strings.HasPrefix(line, "{") {
			continue
		}
		var m map[string]json.RawMessage
		if json.Unmarshal([]byte(line), &m) != nil {
			t.Fatal("invalid fixture JSON")
		}
		if _, ok := m["marketId"]; ok {
			if ledger != nil {
				t.Fatal("duplicate registration")
			}
			registration = m
			var exclusions []string
			if json.Unmarshal(m["excluded"], &exclusions) != nil {
				t.Fatal("bad exclusion array")
			}
			for i := range exclusions {
				exclusions[i] = strings.ToLower(exclusions[i])
			}
			balances := map[string]string{}
			for _, name := range []string{"alice", "bob", "curve", "token", "distributor"} {
				balances[text(m, name)] = text(m, name+"Balance")
			}
			ledger, err = New(Registration{MarketID: text(m, "marketId"), Token: text(m, "token"), TotalSupply: text(m, "totalSupply"), Timestamp: number(m, "timestamp"), Excluded: exclusions, Balances: balances})
			if err != nil {
				t.Fatal(err)
			}
			continue
		}
		if b, ok := m["action"]; ok {
			if ledger == nil || action != nil {
				t.Fatal("unpaired action")
			}
			var a map[string]json.RawMessage
			if json.Unmarshal(b, &a) != nil {
				t.Fatal("bad action")
			}
			action = &Action{Kind: text(a, "kind"), Timestamp: number(a, "timestamp"), From: text(a, "from"), To: text(a, "to"), Account: text(a, "account"), Amount: text(a, "amount")}
			if action.Kind == "burn" {
				action.Kind = "transfer"
			}
			if action.Kind != "view" {
				if err = ledger.Apply(*action); err != nil {
					t.Fatalf("action %d %+v: %v", steps, action, err)
				}
			}
			continue
		}
		if ledger == nil || action == nil {
			t.Fatal("state without action")
		}
		s, err := ledger.View(action.Timestamp)
		if err != nil {
			t.Fatal(err)
		}
		got := map[string]string{"head": strconv.Itoa(int(ledger.Head)), "lastFundingAt": strconv.FormatUint(ledger.LastFundingAt, 10), "updatedAt": strconv.FormatUint(s.UpdatedAt, 10), "supply": s.Supply, "index": s.Index, "indexRemainder": s.IndexRemainder, "rate": s.Rate, "idle": s.Idle, "funded": s.Funded, "paid": s.Paid, "streamCount": strconv.Itoa(len(ledger.Streams))}
		for _, name := range []string{"alice", "bob", "curve"} {
			a := s.Accounts[text(registration, name)]
			got[name+"Balance"] = a.Balance
			got[name+"Claimable"] = a.Claimable
		}
		for key, value := range got {
			if value != text(m, key) {
				t.Fatalf("action %d %+v, %s: Go %s Solidity %s", steps, action, key, value, text(m, key))
			}
		}
		if s.PublicationEligible {
			t.Fatal("fixture must not authorize publication")
		}
		action = nil
		steps++
	}
	if scan.Err() != nil {
		t.Fatal(scan.Err())
	}
	if action != nil || steps < 16 {
		t.Fatalf("incomplete Solidity fixture: %d steps", steps)
	}
	t.Logf("matched %d real Solidity action states, 17 fields each", steps)
}
