// Code generated by scripts/generate_models.py from services/backend-go/openapi/v1.json; DO NOT EDIT.
package readmodel

import "encoding/json"

type SourceBlock struct {
	ChainID          uint64 `json:"chainId"`
	BlockNumber      string `json:"blockNumber"`
	BlockHash        string `json:"blockHash"`
	TransactionHash  string `json:"transactionHash"`
	TransactionIndex uint64 `json:"transactionIndex"`
	LogIndex         uint64 `json:"logIndex"`
}

type SyncStatus struct {
	ChainID         uint64  `json:"chainId"`
	Status          string  `json:"status"`
	BlockNumber     *string `json:"blockNumber"`
	BlockHash       *string `json:"blockHash"`
	Finality        string  `json:"finality"`
	HeadBlockNumber *string `json:"headBlockNumber"`
	HeadBlockHash   *string `json:"headBlockHash"`
	LagBlocks       *string `json:"lagBlocks"`
	Revision        string  `json:"revision"`
}

type PoolKeyReadModel struct {
	Currency0   string `json:"currency0"`
	Currency1   string `json:"currency1"`
	Fee         uint64 `json:"fee"`
	TickSpacing int64  `json:"tickSpacing"`
	Hooks       string `json:"hooks"`
}

type CanonicalRoute struct {
	Router              string `json:"router"`
	Quoter              string `json:"quoter"`
	Hook                string `json:"hook"`
	LaunchLocker        string `json:"launchLocker"`
	GraduationExecutor  string `json:"graduationExecutor"`
	CurveTradingEnabled bool   `json:"curveTradingEnabled"`
	PoolTradingEnabled  bool   `json:"poolTradingEnabled"`
	SourceVersion       uint64 `json:"sourceVersion"`
	LaunchPhase         uint64 `json:"launchPhase"`
}

type CurveProgress struct {
	RealQuoteReserve string `json:"realQuoteReserve"`
	SellableTokens   string `json:"sellableTokens"`
	ReservedTokens   string `json:"reservedTokens"`
	AccruedCurveFees string `json:"accruedCurveFees"`
	ReadyToGraduate  bool   `json:"readyToGraduate"`
}

type MarketIdentityReadModel struct {
	Name            string `json:"name"`
	Symbol          string `json:"symbol"`
	MetadataURI     string `json:"metadataURI"`
	DeployedAt      string `json:"deployedAt"`
	BlockNumber     string `json:"blockNumber"`
	BlockHash       string `json:"blockHash"`
	RuntimeCodeHash string `json:"runtimeCodeHash"`
}

type MarketMetricsReadModel struct {
	Status              string  `json:"status"`
	Reason              string  `json:"reason"`
	Volume24hUSD        *string `json:"volume24hUsd"`
	MarketCapUSD        *string `json:"marketCapUsd"`
	QuoteUSDMidpoint    *string `json:"quoteUsdMidpoint"`
	WindowFromTimestamp string  `json:"windowFromTimestamp"`
	AsOfTimestamp       string  `json:"asOfTimestamp"`
	USDPriceAsOf        *string `json:"usdPriceAsOf"`
	USDPriceSource      *string `json:"usdPriceSource"`
	VolumeBasis         string  `json:"volumeBasis"`
	MarketCapBasis      string  `json:"marketCapBasis"`
}

type MarketReadModel struct {
	MarketID               string                   `json:"marketId"`
	AssetUID               string                   `json:"assetUid"`
	MemeToken              string                   `json:"memeToken"`
	Curve                  string                   `json:"curve"`
	Gauge                  string                   `json:"gauge"`
	QuoteAsset             string                   `json:"quoteAsset"`
	QuoteAssetConfigID     string                   `json:"quoteAssetConfigId"`
	TickerGardenBaselineID string                   `json:"tickerGardenBaselineId"`
	SourceVersion          uint64                   `json:"sourceVersion"`
	LaunchPhase            uint64                   `json:"launchPhase"`
	CurveProgress          CurveProgress            `json:"curveProgress"`
	PoolID                 *string                  `json:"poolId"`
	PoolKey                *PoolKeyReadModel        `json:"poolKey"`
	CanonicalRoute         CanonicalRoute           `json:"canonicalRoute"`
	Source                 SourceBlock              `json:"source"`
	Identity               *MarketIdentityReadModel `json:"identity,omitempty"`
	Metrics                *MarketMetricsReadModel  `json:"metrics,omitempty"`
}

type ConfigReadModel struct {
	Kind   string         `json:"kind"`
	ID     string         `json:"id"`
	Status uint64         `json:"status"`
	Values map[string]any `json:"values"`
	Source SourceBlock    `json:"source"`
}

type QuoteClaimable struct {
	Kind   string `json:"kind"`
	Asset  string `json:"asset"`
	Amount string `json:"amount"`
}

type MemeClaimable struct {
	Kind   string `json:"kind"`
	Asset  string `json:"asset"`
	Amount string `json:"amount"`
}

type UserPositionReadModel struct {
	User         string      `json:"user"`
	AssetUID     string      `json:"assetUid"`
	MarketID     string      `json:"marketId"`
	Free         string      `json:"free"`
	Allocated    string      `json:"allocated"`
	Pending      string      `json:"pending"`
	Active       string      `json:"active"`
	ActivationAt *string     `json:"activationAt"`
	UnlockAt     *string     `json:"unlockAt"`
	Claimable    []Claimable `json:"claimable"`
	Source       SourceBlock `json:"source"`
}

type UserAccountReadModel struct {
	User      string      `json:"user"`
	AssetUID  string      `json:"assetUid"`
	Vault     string      `json:"vault"`
	Deposited string      `json:"deposited"`
	Allocated string      `json:"allocated"`
	Free      string      `json:"free"`
	Source    SourceBlock `json:"source"`
}

type Claimable struct {
	Kind   string `json:"kind"`
	Asset  string `json:"asset"`
	Amount string `json:"amount"`
}
type Snapshot struct {
	ExecutionSpecID      string                  `json:"executionSpecId"`
	ReconciliationAlerts []json.RawMessage       `json:"reconciliationAlerts"`
	Sync                 SyncStatus              `json:"sync"`
	Markets              []MarketReadModel       `json:"markets"`
	Configs              []ConfigReadModel       `json:"configs"`
	Accounts             *[]UserAccountReadModel `json:"accounts,omitempty"`
	Positions            []UserPositionReadModel `json:"positions"`
}
