import {TickerGardenV1Client,type TokenDetailResponse} from './generated/read-api.ts';
import {validateTokenDetail,displayDecimal,circulatingCap,scaledDecimal,feeRows,type DetailIdentity,type DetailPeriod,type FeeConfig} from './tokenDetail.ts';
import {candleVolume} from './candleTable.ts';
export function mountTokenDetail(root:HTMLElement,base:string|null,chain:number,explorer:string){
 const q=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const text=(s:string,v:string)=>root.querySelectorAll<HTMLElement>(s).forEach(e=>e.textContent=v);
 let id:DetailIdentity|null=null,period:DetailPeriod='1H',data:TokenDetailResponse|null=null,fees:FeeConfig|null=null,controller:AbortController|null=null,generation=0,expiry:ReturnType<typeof setTimeout>|undefined,tradeLimit=5,holderLimit=5;
 const amount=(raw:string,d:number)=>displayDecimal(candleVolume(raw,d),6);
 const empty=(tbody:HTMLTableSectionElement,message:string,cols:number)=>{tbody.replaceChildren();const td=tbody.insertRow().insertCell();td.colSpan=cols;td.textContent=message;};
 const sourceLabel=()=>{if(!data)return 'Analytics unavailable';const entries=Object.entries(data.sources).filter(([k])=>['statistics','chart','trades','holders','fees'].includes(k));if(!entries.length)return 'Analytics unavailable — awaiting indexed data';const providers=[...new Set(entries.map(([,s])=>s.provider==='dune'?'Dune':'Indexer'))];const oldest=Math.min(...entries.map(([,s])=>s.asOf));q('[data-detail-source]').title=entries.map(([k,s])=>`${k}: ${s.provider} · ${new Date(s.asOf*1000).toLocaleString()} · block ${s.blockNumber}`).join(' | ');return `${providers.join(' + ')} · Updated ${new Date(oldest*1000).toLocaleTimeString()} · Historical data`;};
 const draw=()=>{
  const canvas=q<HTMLCanvasElement>('[data-detail-chart] canvas'),ctx=canvas.getContext('2d');if(!ctx)return;
  const box=canvas.parentElement!.getBoundingClientRect(),w=Math.max(250,box.width),h=Math.max(180,box.height),dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);
  const chart=data?.chart,active=chart?.points.filter(p=>p.price!==null)??[];ctx.font='12px Arial';ctx.fillStyle='#718092';
  if(!chart||!active.length){ctx.textAlign='center';ctx.fillText(chart?'No trades in this period':'Price history unavailable',w/2,h/2);canvas.setAttribute('aria-label',chart?'No trades in the verified period':'Price history unavailable');return;}
  const prices=active.map(p=>scaledDecimal(p.price!)),low=prices.reduce((a,b)=>a<b?a:b),high=prices.reduce((a,b)=>a>b?a:b),left=76,right=w-8,top=12,bottom=h-30;
  const x=(ts:number)=>left+(ts-chart.from)/(chart.to-chart.from)*(right-left);
  const y=(p:string)=>high===low?(top+bottom)/2:bottom-Number((scaledDecimal(p)-low)*10000n/(high-low))/10000*(bottom-top);
  ctx.textAlign='right';for(let i=0;i<5;i++){const yy=top+(bottom-top)*i/4,n=high-(high-low)*BigInt(i)/4n;ctx.strokeStyle='#e9eee7';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(right,yy);ctx.stroke();ctx.fillStyle='#718092';ctx.fillText(displayDecimal(`${n/10n**36n}.${(n%10n**36n).toString().padStart(36,'0')}`,6),left-8,yy+4);}
  const color=scaledDecimal(active.at(-1)!.price!)>=scaledDecimal(active[0]!.price!)?'#17834b':'#b83f3f';
  // Separate contiguous segments; empty buckets never acquire synthetic prices.
  let segment:Array<{timestamp:number;price:string}>=[];
  const paint=()=>{if(!segment.length)return;ctx.beginPath();segment.forEach((p,i)=>i?ctx.lineTo(x(p.timestamp),y(p.price)):ctx.moveTo(x(p.timestamp),y(p.price)));ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.stroke();if(segment.length===1){ctx.beginPath();ctx.arc(x(segment[0]!.timestamp),y(segment[0]!.price),2.5,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}else{ctx.lineTo(x(segment.at(-1)!.timestamp),bottom);ctx.lineTo(x(segment[0]!.timestamp),bottom);ctx.closePath();const gradient=ctx.createLinearGradient(0,top,0,bottom);gradient.addColorStop(0,color+'30');gradient.addColorStop(1,color+'03');ctx.fillStyle=gradient;ctx.fill();}segment=[];};
  for(const p of chart.points){if(p.price===null)paint();else segment.push({timestamp:p.timestamp,price:p.price});}paint();
  ctx.fillStyle='#718092';ctx.textAlign='left';const label=(ts:number)=>new Date(ts*1000).toLocaleString('en-US',{hour:'2-digit',minute:'2-digit'});ctx.fillText(label(chart.from),left,h-8);ctx.textAlign='right';ctx.fillText(label(chart.to),right,h-8);canvas.setAttribute('aria-label',`${period} ${id?.quoteSymbol} price history; ${active.length} observed intervals. Empty intervals are gaps.`);
 };
 const renderFees=()=>{
  const metrics=q('[data-detail-fee-metrics]'),bar=q('[data-detail-fee-bar]'),rows=q('[data-detail-fee-rows]');metrics.replaceChildren();bar.replaceChildren();rows.replaceChildren();
  if(!fees){metrics.textContent='Unavailable';rows.textContent='Fee configuration unavailable';text('[data-detail-fee-status]','Unavailable');return;}
  const values=feeRows(fees);metrics.style.gridTemplateColumns=`repeat(${values.length},minmax(0,1fr))`;bar.style.gridTemplateColumns=values.map(r=>`${r.percent??1}fr`).join(' ');
  for(const v of values){const cell=document.createElement('div'),strong=document.createElement('strong'),pct=document.createElement('span'),label=document.createElement('small');strong.textContent=v.percent===null?'—':String(v.percent);pct.textContent='%';strong.append(pct);label.textContent=v.label;cell.append(strong,label);metrics.append(cell);const part=document.createElement('span');part.title=`${v.label} ${v.percent??'Unavailable'}%`;part.hidden=v.percent===0;bar.append(part);
   const row=document.createElement('div'),percent=document.createElement('strong'),name=document.createElement('b'),note=document.createElement('span'),total=document.createElement('p'),caption=document.createElement('small');percent.textContent=v.percent===null?'—':`${v.percent}%`;name.textContent=v.label;note.textContent=v.note;caption.textContent='Total allocated';total.append(caption);const amounts=data?.fees?.filter(f=>f.recipient===v.key);total.append(document.createTextNode(data?.fees&&id?(amounts!.map(f=>`${amount(f.amountRaw,f.asset===id!.quoteAsset?id!.quoteDecimals:18)} ${f.asset===id!.quoteAsset?id!.quoteSymbol:id!.symbol}`).join(' + ')||`0 ${id.quoteSymbol}`):'Unavailable'));row.append(percent,name,note,total);rows.append(row);
  }
  text('[data-detail-fee-status]',`${fees.phase===0?'Curve':fees.active===null?'Stake status unavailable':fees.active?'Staking active':'No active stake'} · Holder sharing ${fees.holders?'on':'off'}`);
  text('[data-detail-fee-note]','Percentages apply to protocol fees.');
  text('[data-detail-fee-rules]',`Creator tax ${fees.taxBps/100}% is separate. Totals are actual allocated credits, including creator tax; assets remain separate. ${data?.sources.fees?`${data.sources.fees.provider==='dune'?'Dune':'Indexer'} · ${new Date(data.sources.fees.asOf*1000).toLocaleString()}`:'Historical totals unavailable.'}`);
 };
 const render=()=>{
  const stats=data?.statistics,h=data?.holders;
  text('[data-detail-price]',stats?.price?displayDecimal(stats.price):'Unavailable');text('[data-detail-price-unit]',id?`Price (${id.quoteSymbol})`:'Price');
  text('[data-detail-volume]',stats?.volume24h!==null&&stats?.volume24h!==undefined&&id?`${displayDecimal(stats.volume24h,4)} ${id.quoteSymbol}`:'Unavailable');
  text('[data-detail-holders]',h?h.count.toLocaleString():'Unavailable');text('[data-detail-circulating]',h?amount(h.circulatingSupplyRaw,18):'Unavailable');
  const cap=circulatingCap(stats?.price,h?.circulatingSupplyRaw);text('[data-detail-cap]',cap&&id?`${displayDecimal(cap,2)} ${id.quoteSymbol}`:'Unavailable');
  const active=data?.chart?.points.filter(p=>p.price!==null)??[];let change='Unavailable';if(active.length>1){const first=scaledDecimal(active[0]!.price!),last=scaledDecimal(active.at(-1)!.price!);const bps=(last-first)*10000n/first;change=`${bps>=0n?'+':'−'}${(bps<0n?-bps:bps)/100n}.${((bps<0n?-bps:bps)%100n).toString().padStart(2,'0')}% (${period})`;q('[data-detail-change]').classList.toggle('ref-negative',bps<0n);}text('[data-detail-change]',change);
  const trades=q<HTMLTableSectionElement>('[data-detail-trades-body]');empty(trades,data?.trades?'No trades in the verified range.':'Trade history unavailable.',6);
  if(data?.trades?.length){trades.replaceChildren();for(const t of data.trades.slice(0,tradeLimit)){const row=trades.insertRow();row.title=t.classification==='unclassified'?'Contract caller; wallet identity unverified':'Internal reward conversion';const values=[new Date(t.timestamp*1000).toLocaleTimeString('en-US'),t.side==='buy'?'Buy':'Sell',displayDecimal(t.price),amount(t.memeRaw,18),amount(t.quoteRaw,id!.quoteDecimals),t.actor?`${t.actor.slice(0,6)}…${t.actor.slice(-4)}`:'Unavailable'];values.forEach((v,i)=>{const c=row.insertCell();c.textContent=v;if(i===1)c.className=t.side;if(i===0){const link=document.createElement('a');link.href=`${explorer}/tx/${t.txHash}`;link.target='_blank';link.rel='noopener noreferrer';link.textContent=v;c.replaceChildren(link);}});}}
  const holders=q<HTMLTableSectionElement>('[data-detail-holders-body]');empty(holders,h?'No included holders.':'Holder history unavailable.',3);if(h?.items.length){holders.replaceChildren();for(const v of h.items.slice(0,holderLimit)){const row=holders.insertRow(),bp=BigInt(h.totalSupplyRaw)?BigInt(v.balanceRaw)*10000n/BigInt(h.totalSupplyRaw):0n;for(const s of [`${v.account.slice(0,6)}…${v.account.slice(-4)}`,amount(v.balanceRaw,18),`${bp/100n}.${(bp%100n).toString().padStart(2,'0')}%`])row.insertCell().textContent=s;row.title=v.account;}}
  q('[data-detail-more-trades]').hidden=!data?.trades||tradeLimit>=data.trades.length;q('[data-detail-more-holders]').hidden=!h||holderLimit>=h.items.length;text('[data-detail-source]',sourceLabel());renderFees();draw();
 };
 const refresh=async()=>{const own=++generation;controller?.abort();const abort=new AbortController();controller=abort;clearTimeout(expiry);data=null;render();if(!id||!base)return;const identity=id,chosen=period;const timer=setTimeout(()=>abort.abort(),12000);text('[data-detail-source]','Loading analytics…');try{const api=new TickerGardenV1Client(base,(input,init)=>fetch(input,{...init,signal:abort.signal}));const raw=await api.getTokenDetail({marketId:identity.marketId,period:chosen});const next=validateTokenDetail(raw,chain,identity,chosen);if(own!==generation||abort.signal.aborted)return;data=next;render();const times=Object.values(next.sources).map(s=>s.asOf);if(times.length)expiry=setTimeout(()=>{if(own===generation){data=null;render();}},Math.max(0,(Math.min(...times)+1200)*1000-Date.now()));}catch{if(own===generation){data=null;render();}}finally{clearTimeout(timer);if(own===generation)controller=null;}};
 for(const b of root.querySelectorAll<HTMLButtonElement>('[data-detail-period]'))b.onclick=()=>{period=b.dataset.detailPeriod as DetailPeriod;root.querySelectorAll('[data-detail-period]').forEach(v=>{v.classList.toggle('active',v===b);v.setAttribute('aria-pressed',String(v===b));});void refresh();};
 q('[data-detail-more-trades]').onclick=()=>{tradeLimit+=10;render();};q('[data-detail-more-holders]').onclick=()=>{holderLimit+=10;render();};q('[data-detail-refresh]').onclick=()=>void refresh();
 // Statistical analytics are intentionally refreshed every 10 minutes; this is
 // independent from live transaction, position, reward, and pricing refreshes.
 const observer=new ResizeObserver(draw);observer.observe(q('[data-detail-chart]'));const timer=setInterval(()=>{if(id&&document.visibilityState==='visible'&&navigator.onLine)void refresh();},600000);
 const visibility=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void refresh();else{generation++;controller?.abort();clearTimeout(expiry);data=null;render();}};
 document.addEventListener('visibilitychange',visibility);window.addEventListener('online',visibility);window.addEventListener('offline',visibility);
 render();return{setMarket(value:DetailIdentity|null){id=value;fees=null;tradeLimit=5;holderLimit=5;void refresh();},setFeeConfig(value:FeeConfig|null){fees=value;renderFees();},stop(){generation++;controller?.abort();clearInterval(timer);clearTimeout(expiry);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('online',visibility);window.removeEventListener('offline',visibility);observer.disconnect();id=null;data=null;}};
}
