import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { legacyV1Abis, V1_ABI_FINGERPRINT } from '../../../apps/web/src/v1/generated/legacy-abis.ts';
import { currentV4Abis } from '../../../apps/web/src/v1/generated/abis.ts';

const modules = [
  'AllocationManager', 'ApprovedQuoteRegistry', 'CreatorRevenueRegistry', 'GraduationExecutor', 'LaunchTemplateRegistry',
  'MarketRegistryV1', 'MemeStockGauge', 'OfficialStockRegistryV1', 'ProtocolFeeVault', 'TickerGardenBaselineRegistry',
  'TickerGardenCurve', 'TickerGardenFactoryV1', 'TickerGardenMemeHook', 'TickerMemeTokenV1', 'UserStockVault',
] as const;
const entries = Object.fromEntries(modules.map((module) => [module, legacyV1Abis[module].filter((item) => item.type === 'event')])) as Record<string, unknown[]>;
const readFunctions = {
  AllocationManager: ['rageQuitSettlementPending'],
  MarketRegistryV1: ['canonicalPoolId', 'canonicalPoolKey', 'canonicalRoute', 'graduationExecutor', 'market', 'marketIdByToken', 'quoter', 'swapRouter'],
  MemeStockGauge: ['activationSnapshot', 'positionOf'],
  TickerGardenCurve: ['accruedCurveFees', 'creatorTaxBps', 'quoteAsset', 'readyToGraduate', 'realQuoteReserve', 'reservedTokens', 'sellableTokens'],
  TickerMemeTokenV1: ['deployedAt', 'factory', 'marketId', 'metadataURI', 'name', 'symbol'],
  UserStockVault: ['allocated', 'allocation', 'deposited', 'freeBalanceOf'],
} as const;
const readEntries = Object.fromEntries(Object.entries(readFunctions).map(([module, names]) => [
  module,
  legacyV1Abis[module as keyof typeof legacyV1Abis].filter((item) => item.type === 'function' && names.includes(item.name as never)),
])) as Record<string, unknown[]>;
entries.UniswapV4PoolManager = [{
  type: 'event', name: 'Swap', anonymous: false,
  inputs: [
    { name: 'id', type: 'bytes32', indexed: true }, { name: 'sender', type: 'address', indexed: true },
    { name: 'amount0', type: 'int128', indexed: false }, { name: 'amount1', type: 'int128', indexed: false },
    { name: 'sqrtPriceX96', type: 'uint160', indexed: false }, { name: 'liquidity', type: 'uint128', indexed: false },
    { name: 'tick', type: 'int24', indexed: false }, { name: 'fee', type: 'uint24', indexed: false },
  ],
}];
const holderEvents: Array<readonly [string, readonly (readonly [string, string, boolean])[]]> = [
  ['HolderStreamMarketRegistered', [['marketId', 'bytes32', true], ['token', 'address', true], ['quote', 'address', false], ['vault', 'address', false]]],
  ['HolderAssetFunded', [['marketId', 'bytes32', true], ['asset', 'address', true], ['amount', 'uint256', false]]],
  ['HolderMemeRestored', [['marketId', 'bytes32', true], ['account', 'address', true], ['amount', 'uint256', false]]],
  ['HolderRewardsQueued', [['marketId', 'bytes32', true], ['amount', 'uint256', false]]],
  ['HolderStreamFunded', [['marketId', 'bytes32', true], ['amount', 'uint256', false], ['end', 'uint64', false]]],
  ['HolderStreamClaimed', [['marketId', 'bytes32', true], ['account', 'address', true], ['asset', 'address', false], ['amount', 'uint256', false]]],
  ['IdleRewardsRestarted', [['marketId', 'bytes32', true], ['scaledAmount', 'uint256', false], ['end', 'uint64', false]]],
  ['HolderFundingIntervalUpdated', [['marketId', 'bytes32', true], ['previousInterval', 'uint256', false], ['newInterval', 'uint256', false]]],
];
entries.HolderRewardsDistributorV1 = holderEvents.map(([name, inputs]) => ({
  type: 'event', name, anonymous: false,
  inputs: inputs.map(([inputName, type, indexed]) => ({ name: inputName, type, indexed })),
}));

const legacySource = await readFile(path.resolve(process.cwd(), '../../apps/web/src/v1/generated/legacy-abis.ts'));
const sourceSha256 = createHash('sha256').update(legacySource).digest('hex');
const currentEvents = Object.fromEntries([...modules, 'HolderRewardsDistributorV1' as const].map(module => [module, currentV4Abis[module].filter(item => item.type === 'event')]));
const output = `// Generated by scripts/generate-f72-event-abis.ts. Do not edit.\n`
  + `export const F72_EVENT_ABI_SOURCE = ${JSON.stringify({ abiFingerprint: V1_ABI_FINGERPRINT, legacySourceSha256: sourceSha256 })} as const;\n`
  + `export const f72EventAbis = ${JSON.stringify(entries)} as const;\n`
  + `export const currentEventAbis = ${JSON.stringify(currentEvents)} as const;\n`
  + `export const f72ReadAbis = ${JSON.stringify(readEntries)} as const;\n`;
const outputPath = path.resolve(process.cwd(), 'packages/events/src/f72-abis.generated.ts');
if (process.argv.includes('--check')) {
  if (await readFile(outputPath, 'utf8') !== output) throw new Error('f72 event ABI output is stale');
  console.log(JSON.stringify({ status: 'current', modules: Object.keys(entries).length, sourceSha256 }));
} else {
  await writeFile(outputPath, output);
  console.log(JSON.stringify({ status: 'generated', modules: Object.keys(entries).length, sourceSha256 }));
}
