import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CURRENT_RELEASE_ID } from '../packages/events/src/index.ts';

const sourcePath = path.resolve(process.cwd(), '../../apps/web/public/integration/rh-685b5c20.json');
const bytes = await readFile(sourcePath);
const source = JSON.parse(bytes.toString('utf8')) as { chainId: number; releaseId: string; configs: unknown[]; assets: unknown[] };
if (source.chainId !== 46630 || source.releaseId !== CURRENT_RELEASE_ID || !Array.isArray(source.configs) || !Array.isArray(source.assets)) {
  throw new Error('current integration bootstrap identity is invalid');
}
const normalize = (value: unknown): unknown => {
  if (typeof value === 'string' && /^0x[0-9a-fA-F]{40}$/.test(value)) return value.toLowerCase();
  if (Array.isArray(value)) return value.map(normalize);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, nested]) => [key, normalize(nested)]));
  return value;
};
const records = normalize([...source.configs, ...source.assets]) as unknown[];
const sourceSha256 = createHash('sha256').update(bytes).digest('hex');
const output = `// Generated by scripts/generate-f72-bootstrap.ts. Do not edit.\n`
  + `export type BootstrapConfig = { readonly kind: 'asset' | 'quote' | 'baseline' | 'template'; readonly id: \`0x\${string}\`; readonly status: number; readonly values: Readonly<Record<string, string | number | boolean>>; readonly source: { readonly chainId: number; readonly blockNumber: string; readonly blockHash: \`0x\${string}\`; readonly transactionHash: \`0x\${string}\`; readonly transactionIndex: number; readonly logIndex: number } };\n`
  + `export const F72_BOOTSTRAP_SOURCE = ${JSON.stringify({ sourceSha256, releaseId: source.releaseId, chainId: source.chainId })} as const;\n`
  + `export const f72BootstrapConfigs: readonly BootstrapConfig[] = ${JSON.stringify(records)};\n`;
const outputPath = path.resolve(process.cwd(), 'packages/config-projector/src/f72-bootstrap.generated.ts');
if (process.argv.includes('--check')) {
  if (await readFile(outputPath, 'utf8') !== output) throw new Error('f72 bootstrap output is stale');
  console.log(JSON.stringify({ status: 'current', records: records.length, sourceSha256 }));
} else {
  await writeFile(outputPath, output);
  console.log(JSON.stringify({ status: 'generated', records: records.length, sourceSha256 }));
}
