const topics = [
  ['basics', 'Getting Started'], ['create', 'Launch A Token'],
  ['trading', 'Trading & Bloom'], ['staking', 'Stock Staking'],
  ['rewards', 'Claim Rewards'], ['help', 'Help'],
] as const;

const answers = [
  ['basics', 'What Is TickerGarden?', 'Launch a community token, trade it, and share trading fees with its creator, eligible holders or Stock stakers. A token is not company equity and does not track a stock price.'],
  ['basics', 'What Do I Need To Start?', 'Connect your wallet on the network shown in the footer. Keep ETH for transaction fees and the required asset for buying or staking. Testnet assets are for testing.'],
  ['basics', 'Paired Asset Or Staking Asset?', 'The paired asset is what you use to buy and sell the token. The staking asset is the Stock accepted for staking in that market. They can be different assets; holding the community token is not the same as staking Stock.'],
  ['create', 'How Do I Launch A Token?', 'Open <a href="/create">Create</a>, add a name, ticker and image, then choose a paired asset and any optional fee-sharing features. You first sign a message to authorize publishing your image and details; this signature does not launch the token or approve asset spending. After publication, review any required asset approval or purchase, then confirm the launch transaction. The success page provides a link to your token after the transaction is confirmed.'],
  ['create', 'What Can I Upload?', 'Use PNG, JPG or WebP up to 2 MB. Names allow 64 characters, tickers 16 letters or numbers, and descriptions 300 characters. Description, website and X are optional.'],
  ['create', 'Where Are My Token Details Published?', 'Your image and metadata are published to IPFS before the launch transaction is submitted. Published content may remain available even if you cancel the wallet request or the launch transaction fails. After creation, use the token information pack and listing links to submit your details to other platforms. Publication does not automatically create a third-party listing.'],
  ['create', 'What Is Developer Buy?', 'An optional first purchase included with your launch. Leave it blank to skip. The flow acquires the actual configured Quote asset; for an ERC-20 Quote, approve that Quote first when prompted, then review the amount and confirm.'],
  ['create', 'Which Settings Should I Review?', 'Choose whether to enable Stock staking and Holder fee sharing. Creator tax is an extra trading fee from 0% to 5%, with up to two decimal places. The paired asset, staking option, holder-sharing option and creator tax are fixed at launch.'],
  ['create', 'What Is Token Fee Burning?', 'This is an immutable opt-in at creation. When enabled, Creator and Staker fees paid in the created token, including creator tax, are destroyed when a reward claim is processed, even if the claim requests the paired asset only. Their paired-asset fees are paid normally. Holder fees paid in the created token are destroyed by FeeVault during funding settlement and are never funded to the HolderRewardsDistributor; holder snapshots therefore apply to the paired asset only. No burn occurs on swaps or transfers, and the burn is a real token supply reduction rather than a transfer to a dead address. Unclaimed Creator or Staker fees remain pending until settlement. Platform fees are unaffected.'],
  ['trading', 'Growing Or Bloomed?', 'Growing tokens trade on a bonding curve. When the Bloom target is reached, the final buy creates the liquidity pool and the token becomes Bloomed. Trading then uses that pool, with its initial liquidity permanently locked.'],
  ['trading', 'What Is The Bloom Target?', 'The net paired asset needed to complete the curve, excluding fees and virtual reserves. Check the target on Create or the token page: it depends on the asset and network. A buy above the remaining curve amount only uses what is needed and refunds the excess.'],
  ['trading', 'How Do I Buy Or Sell?', 'Open a token, select Buy or Sell and enter an amount. Check the output, trading fee and price impact, then confirm in your wallet. Token approval may be required first; approval alone does not complete the trade.'],
  ['trading', 'Can My Final Price Change?', 'Yes. Quotes refresh while you trade, and other trades can change the price before confirmation. Price impact shows how much your trade moves the pool price. The trading form currently has no user-set slippage limit.'],
  ['trading', 'What Is Anti-Snipe?', 'Buys during the first 5 seconds after launch may carry an additional, declining fee. Check the quoted fee before buying.'],
  ['trading', 'How are trading fees shared?', 'A completed trade creates the fee; indexing and allocation can appear later, so an allocated total is not the same as an immediately claimable balance. The token page shows the current split between Creator, Holder, Staker and Platform. Stakers only earn after Bloom with active stake. Creator tax goes entirely to the creator wallet and is separate from the base fee split. Any pool fee shown in the quote is charged separately by the liquidity pool and is excluded from these shares.'],
  ['trading', 'What Happens To Fees Earned By The Locked LP?', 'LP fees first accrue to the locked position in Uniswap v4; they do not automatically become trading liquidity or trigger an autoswap. Anyone can collect them into the same Locker. A governance-designated Keeper can optionally add matching amounts back to the original locked position, within explicit input limits and a deadline. No compounding schedule is enabled by this guide. Unmatched fees stay in the Locker. Funds never pass through the Keeper wallet, and LP principal cannot be withdrawn. These fees are separate from FeeVault rewards and token fee burning. This feature requires the new contract release and is not live on existing deployments.'],
  ['staking', 'What Does Enable Staking Rewards Do?', 'It lets users stake the selected Stock and share that market’s trading fees after Bloom. The creator must enable it at launch. A Growing market can show staking information, but new stake opens only after Bloom.', 'staking-rewards'],
  ['staking', 'How Do I Stake Stock?', 'Go to <a href="/stake">Stake</a>, search for a market and select Add. Enter an amount within your wallet balance. Your total position in the selected market must meet its displayed minimum. The planned Stock minimum is 0.5, but administrators can update the asset setting. An addition can be smaller than the minimum when your resulting position still meets it; positions in other markets do not count. Approve the selected Stock Token if needed, then confirm Stake. My Markets lists your positions.'],
  ['staking', 'When Does My Stake Earn Rewards?', 'New stake starts earning after 30 seconds. Rewards depend on your active share of that market’s stake and the fees it generates. Adding more before activation restarts the wait for the pending amount; existing active stake keeps earning. There is no fixed yield.'],
  ['staking', 'Can Reward Accounting Fail?', 'If Staker reward accounting fails during a pool trade, that trade can still complete. The failed new Staker fee share is forfeited to the Platform; it is not reassigned to later stakers. Previously earned rewards stay recorded, and later trades still attempt normal reward allocation.'],
  ['staking', 'How Does Normal Withdrawal Work?', 'New stake starts a 24-hour lock. Each addition restarts the lock for your entire position, including normal reward claims. After the countdown ends, Unstake all returns the full allocated Stock Token principal to your wallet; partial withdrawal is not supported. Normal withdrawal does not automatically claim rewards, and rewards already earned remain available to claim separately.'],
  ['staking', 'How Is Emergency Principal Exit Different?', 'The protocol also defines a user-initiated rageQuit path that can return the full allocated Stock Token principal without waiting for the 24-hour lock. It permanently forfeits every unclaimed paired-asset and created-token reward in that position, and reward-accounting cleanup may finish later. There is no rageQuit button in the frontend. Users must call the verified external interface or canonical contract route themselves after checking the market and transaction details.'],
  ['rewards', 'Where Do I Claim Each Type Of Reward?', 'Use <a href="/claim#creator">Claim → Creator</a> for creator fees, <a href="/claim#treasury">Claim → Holder</a> for holder rewards, and <a href="/stake">Stake</a> for staking rewards. These are separate balances.'],
  ['rewards', 'How Do Creator Rewards Work?', 'The Creator tab lists tokens launched by your connected wallet. Fees are paid to the designated creator wallet. If you chose a different creator wallet at launch, that address receives the fees.'],
  ['rewards', 'Can Creator Fee Rights Be Transferred?', 'The current beneficiary can nominate a new wallet, which must accept the handoff. Future fees then belong to the new beneficiary; previously earned fees stay with the beneficiary of their original version. This transfers fee rights, not token balances or control over minting. There is no transfer control in the frontend. The Creator must request a transfer by email or another published project contact channel. Support cannot bypass on-chain authority: the current beneficiary must still nominate the wallet and the new beneficiary must accept it through a verified contract interface.'],
  ['rewards', 'Who Earns Holder Rewards?', 'A market must have Holder fee sharing enabled at launch. It assigns half of the creator’s base-fee share to eligible holders of the created token; creator tax is excluded. FeeVault funds the HolderRewardsDistributor, then a trusted snapshot publisher posts a funded wallet-balance root. Only the direct wallet balance of that token at the snapshot is included; LP and other indirect holdings are excluded. Selling after the snapshot does not remove that round’s entitlement, and no extra staking or deposit is required.'],
  ['rewards', 'When Can I Claim Holder Rewards?', 'Holder rewards use funded wallet snapshots and published Merkle roots. The publication cadence is an off-chain operational policy; the contract does not promise a fixed 24-hour or 7-day payout period. Check Claim for the published round, proof and remaining funded budget.'],
  ['rewards', 'Which Reward Assets Can I Claim?', 'With token fee burning off, claims pay the selected paired asset, created token, or both in their original form. With it on, Creator and Staker fees paid in the created token are burned during any reward claim, and Holder fees paid in that token are burned before snapshot funding; only paired-asset rewards are paid out. Platform fees are unaffected. There is no on-chain conversion or fallback.'],
  ['help', 'Why Is A Reward Not Claimable Yet?', 'The market may not have earned fees, your stake may still be locked, or a holder distribution may still be settling. Check the status on the relevant rewards page. Displayed fee totals are not your claimable balance.'],
  ['help', 'My Transaction Is Pending. What Should I Do?', 'Check the transaction status at the bottom of the page or open it in the explorer. Do not submit again while it is pending. A launch in progress is restored after refreshing. Rejected wallet requests do not complete the action.'],
  ['help', 'Why Do Statistics Update Later?', 'Market and protocol statistics depend on indexing and may be delayed or unavailable. Transaction status is tracked separately. A dash means data is not available yet, not necessarily zero.'],
  ['help', 'Does This Guide Apply To Older Markets?', 'This guide describes the latest contract version. Existing markets retain their original reward rules; the Claim page shows the distribution supported by the selected market. A new deployment does not migrate an older market or its rewards.'],
  ['help', 'How Do I Check The Right Token?', 'Compare the contract address, not just the name or ticker. Different tokens can look alike, and multiple markets can use the same Stock. Review <a href="/risks">Risks</a> before using funds you cannot afford to lose.'],
];

export default {
  title: 'Docs — TickerGarden',
  html: `
<main class="page docs-page">
  <header class="page-hero docs-heading">
    <div><div class="kicker"><i class="ph ph-book-open-text" aria-hidden="true"></i>User Guide</div><h1>Docs</h1><p>Launch, trade, stake and claim. The essentials in one place.</p></div>
  </header>
  <label class="docs-search"><i class="ph ph-magnifying-glass" aria-hidden="true"></i><input data-docs-search type="search" aria-label="Search docs" placeholder="Search the docs" autocomplete="off" /></label>
  <div class="docs-body">
    <nav class="docs-toc" aria-label="Documentation topics"><span class="docs-toc-label">Contents</span>${topics.map(([id, label]) => `<a href="#docs-${id}">${label}<i class="ph ph-arrow-up-right" aria-hidden="true"></i></a>`).join('')}</nav>
    <div class="docs-content">${topics.map(([topic, label], index) => `<section class="docs-section" id="docs-${topic}" data-docs-section aria-labelledby="docs-title-${topic}"><header class="docs-section-heading"><span aria-hidden="true">${String(index + 1).padStart(2, '0')}</span><h2 id="docs-title-${topic}">${label}</h2></header>${answers.filter(([id]) => id === topic).map(([, question, answer, id]) => `<article class="docs-article" data-docs-article${id ? ` id="${id}"` : ''}><h3>${question}</h3><p>${answer}</p></article>`).join('')}</section>`).join('')}
      <p class="docs-empty" data-docs-empty role="status" hidden>No matching articles. Try another search.</p>
    </div>
  </div>
</main>`,
};
