import { productionContracts } from './docs-production-contracts.ts';

const topics = [
  ['basics', 'Overview'], ['create', 'Launch a token'], ['trading', 'Trading & Bloom'],
  ['stock', 'Stock Tokens'], ['fees', 'Fees & burns'], ['staking', 'Stock staking'],
  ['rewards', 'Claim rewards'], ['revenue', 'Project economics'], ['governance', 'Market settings'],
  ['network', 'Network'], ['contracts', 'Contract addresses'], ['risks', 'Risk disclosure'], ['help', 'Help & support'],
] as const;
const p = (text: string) => `<p>${text}</p>`;
const list = (items: string[]) => `<ul>${items.map(item => `<li>${item}</li>`).join('')}</ul>`;
const table = (caption: string, headings: string[], rows: string[][]) => `<div class="docs-table-wrap"><table><caption>${caption}</caption><thead><tr>${headings.map(h => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;

const articles: readonly (readonly [string, string, string, string?])[] = [
  ['basics', 'A garden for community tokens', p('TickerGarden is a place to launch and trade community tokens on Robinhood Chain. Each token is associated with an approved Stock Token, and its creator can enable fee sharing for token holders and Stock stakers.') + p('A community token is not company equity. It does not track a stock price, give you rights to the associated stock, or offer redemption against Stock reserves.')],
  ['basics', 'Security review & audit status', p('TickerGarden’s contracts have undergone rigorous internal security testing and code review. <strong>They have not yet undergone an independent external audit.</strong>') + p('Internal reviews are an important part of our security process, but they do not replace independent assessment or eliminate smart contract risk. Please consider this when deciding whether and how much to use the protocol.'), 'security-review'],
  ['basics', 'From launch to rewards', `<ol class="docs-journey"><li><strong>Launch</strong><span>Choose a Stock association, paired asset and fee-sharing options.</span></li><li><strong>Grow</strong><span>Buy and sell on the bonding curve until the Bloom target is reached.</span></li><li><strong>Bloom</strong><span>Trading moves into a Uniswap v4 pool with permanently locked initial liquidity. Enabled Stock staking opens.</span></li></ol>` + p('Trading fees fund rewards. There is no fixed yield or ongoing token issuance for staking. Every approval, launch, trade and claim requires a wallet transaction.')],
  ['create', 'Choose your market', p('Open <a href="/create">Launch</a> and add your token’s name, ticker, image and optional links. Select its Stock association and paired asset. The paired asset is what buyers pay and sellers receive; it can differ from the Stock used for staking.') + list(['Enable Stock staking if you want Stock holders to share fees after Bloom.', 'Enable Holder fee sharing to assign half of the creator’s base-fee share to eligible token holders.', 'Set an optional creator tax from 0% to 5%, with up to two decimal places.', 'Choose whether rewards paid in the created token should be burned.']) + p('These market choices are fixed at launch. Review the supply, Bloom target and fees shown in the launch preview before signing.')],
  ['create', 'Publish and confirm', p('Upload a PNG, JPG or WebP image up to 2 MB. Names allow 64 characters and tickers 16 letters or numbers. A description of up to 300 characters, website and X profile are optional.') + p('First sign a message to authorize publishing your image and token details. This signature does not launch the token or approve asset spending. Published content can remain available even if you cancel the launch.') + p('An optional Developer Buy makes a first purchase with the launch. Approve the paired asset if prompted, then confirm the launch transaction. Wait for confirmation before opening your token. The information pack helps with third-party submissions; it does not automatically list your token elsewhere.')],
  ['create', 'Troubleshooting a launch', p('A launch can include several steps: publishing your details, buying a missing paired asset, approving that asset and submitting the launch. A completed paired-asset purchase stays in your wallet if a later step stops. An approval only authorizes spending; it does not create a token. Continue from the updated wallet balance.') + p('Keep enough ETH for the launch fee, an optional Developer Buy and network fees. A failed onchain transaction may still use network fees. When the app buys a missing paired asset with ETH, the maximum payment includes up to 10% above the estimate you confirmed. If the new cost exceeds that limit, refresh the quote and review the new total.') + p('After a transaction is sent, the app checks its outcome automatically. A confirmed failure differs from a result that is still unknown; wait for the app to finish checking before trying again. If the token was created but its page is still preparing, the app resumes that project instead of requiring another launch.') + p('For help, message us on <a href="https://x.com/TickerGarden" target="_blank" rel="noopener noreferrer">X</a> or email <a href="mailto:info@tickergarden.com">info@tickergarden.com</a>. Include the network, public wallet address, token name, approximate time and error reference if available. Never share a recovery phrase, private key or wallet signature.')],
  ['trading', 'Growing: the bonding curve', p('Growing tokens trade against their chosen paired asset on a bonding curve. Buys raise the curve price and sells lower it. The Bloom target measures the net paired asset collected, excluding fees.') + p('Mainnet launch targets start at 3 ETH for ETH pairs and 7,000 USDG for USDG pairs. Stock-paired markets have asset-specific targets. Use the target displayed for your selected market; a Stock-denominated target is not a fixed dollar value.')],
  ['trading', 'Bloomed: a locked liquidity pool', p('The final curve buy creates the Uniswap v4 liquidity pool and completes Bloom in the same transaction. An order above the remaining curve capacity uses only what is needed and refunds the excess. If the pool cannot be created, the purchase does not complete.') + p('After Bloom, trading uses the pool and initial liquidity is permanently locked. Bloom is a trading milestone, not an endorsement, a price guarantee or a guarantee that you can sell at any size.')],
  ['trading', 'Explore rankings', p('Recent buys puts tokens with the latest confirmed buys first. A token appears once, even after multiple buys. Choose Show latest when new buys arrive while you are browsing.') + p('Market cap rankings update every 20 minutes. Displayed values may update sooner, so their current order can differ from those values. Tokens without a value show a dash and rank last. Newly launched tokens enter the next market cap ranking; use Newest or search to find them sooner.')],
  ['trading', 'Review every trade', p('Open a token, choose Buy or Sell and enter an amount. Review the expected output, fees and price impact, then confirm in your wallet. A required asset approval is a separate step and does not complete the trade.') + p('Price impact is the price movement caused by your order. Other trades can also move the price before your transaction lands. Quotes are estimates; the trading form currently has no user-set slippage limit. Buys during the first 5 seconds after launch may include an additional, declining anti-snipe fee.')],
  ['stock', 'Two uses for Stock Tokens', table('Stock association and paired asset serve different purposes', ['Role', 'What it means'], [ ['Associated Stock', 'The approved Stock linked to a community token. If staking is enabled, this is the asset users stake after Bloom.'], ['Paired asset (Quote)', 'The asset used to buy, sell and measure the Bloom target. It may be ETH, USDG or an approved Stock Token.'] ]) + p('The supported asset list includes 194 Robinhood official Stock Tokens. Paired-asset choices also include ETH and USDG. Choose from the assets shown on Launch; availability for new launches may change. Check the token address as well as its ticker.')],
  ['stock', 'What a Stock association does not mean', p('Buying a community token does not buy its associated Stock. Staked Stock belongs to the depositor and is held in the Stock vault; it is not a reserve that community token holders can redeem. Multiple community tokens can share the same Stock association, with separate markets and rewards.') + p('Stock Tokens also depend on their issuer and underlying asset rules, including possible transfer restrictions or contract changes. TickerGarden’s admission does not remove those risks.')],
  ['fees', 'How trading fees are shared', p('After Bloom, the base protocol trading fee is 1%. Growing markets use the curve fee set at launch. Creator tax and any pool fee are separate from the base-fee split; check the transaction quote for the total.') + table('Share of the base protocol fee', ['Market state', 'Creator', 'Holder', 'Staker', 'Platform'], [ ['Growing, or no active stake', '70%', '—', '—', '30%'], ['Same, with Holder sharing', '35%', '35%', '—', '30%'], ['Bloomed, with active stake', '40%', '—', '30%', '30%'], ['Same, with Holder sharing', '20%', '20%', '30%', '30%'] ]) + p('Creator tax goes entirely to the creator beneficiary and is excluded from Holder sharing. Stakers earn only from their own market’s fees after their stake becomes active. Fees earned before activation are not shared retroactively.')],
  ['fees', 'Optional token fee burning', p('When enabled at launch, Creator and Staker rewards paid in the created token are burned when a reward claim is processed, including claims requesting only the paired asset. Holder rewards paid in the created token are burned before they become available to claim. Paired-asset rewards are paid normally, and Platform fees are unaffected.') + p('This reduces token supply; it does not burn ordinary swaps or wallet transfers. Unclaimed Creator and Staker token rewards are burned when a claim is processed. Burning does not guarantee a higher price.')],
  ['fees', 'Fees earned by locked liquidity', p('Fees earned by locked liquidity are separate from Creator, Holder and Staker rewards. They may be reinvested into the same pool to increase its locked liquidity.') + p('Reinvestment has no fixed schedule and requires no action from users. Fees that have not been reinvested remain with the locked position. The locked liquidity principal cannot be withdrawn.')],
  ['staking', 'Stake Stock after Bloom', p('The creator must enable staking at launch. New stake opens only after Bloom. Go to <a href="/stake">Stake</a>, choose a market and select Add. Approve the selected Stock if needed, then confirm the stake.',) + p('The starting minimum is 0.5 Stock per market position. Minimums may change; check the value shown for your selected market. Smaller additions are allowed when your resulting position meets that minimum. The same principal cannot count in two markets at once.'), 'staking-rewards'],
  ['staking', 'Activation and the withdrawal lock', p('New stake starts earning after 30 seconds. Adding more before activation restarts the wait for the pending amount; existing active stake keeps earning.') + p('Each new stake or addition starts a 24-hour lock for the entire position, including normal reward claims. After it expires, Unstake all returns the full allocated Stock principal to your wallet. Partial withdrawal is not supported. Withdrawal does not automatically claim rewards; earned rewards remain available separately.')],
  ['staking', 'Emergency principal exit', p('The emergency exit can return the full allocated Stock Token principal without waiting for the 24-hour lock. It permanently forfeits every unclaimed paired-asset and created-token reward in that position.') + p('Emergency exit is not available through the app. Use Unstake all for normal withdrawals. If you need an emergency exit, consult the project’s published support channels and review the loss of rewards before signing. Support will never need your private key or seed phrase.')],
  ['rewards', 'Where to claim', table('Each reward has its own balance', ['Reward', 'Where to go', 'What to check'], [ ['Creator', '<a href="/claim#creator">Claim → Creator</a>', 'Connect the designated creator beneficiary wallet.'], ['Holder', '<a href="/claim#treasury">Claim → Holder</a>', 'A published reward round must include your wallet.'], ['Staker', '<a href="/stake">Stake</a>', 'Your position must have earned fees and its normal claim lock must have expired.'] ]) + p('A displayed fee total is not your immediately claimable balance. Newly earned fees may take time to appear as available rewards.')],
  ['rewards', 'Who Earns Holder Rewards?', p('Holder fee sharing must be enabled at launch. Eligible holders receive half of the creator’s base-fee share, excluding creator tax. Holder rewards use periodic records of direct wallet balances, called snapshots, published by the project. LP and other indirect holdings are excluded.') + p('No extra staking or deposit is required. Selling after a snapshot does not remove your entitlement to that round. Eligibility depends on the published snapshot, not your balance when you press Claim.')],
  ['rewards', 'When Can I Claim Holder Rewards?', p('Claims become available when a funded reward round is published. There is no fixed daily or weekly payout schedule. Check Claim for your available round and balance.')],
  ['rewards', 'Which Reward Assets Can I Claim?', p('With token fee burning off, choose the paired asset, created token or both. Rewards are paid in their original form, without automatically exchanging one asset for another. With burning on, only paired-asset rewards are paid to Creator, Holder and Staker recipients; created-token rewards are burned as described above.')],
  ['revenue', 'Platform token and future airdrop', p('TickerGarden has not launched a platform token. Tokens created by users on TickerGarden are independent community tokens, not the platform’s own token.') + p('A future airdrop is planned. Timing, eligibility and distribution details will be announced through official channels. Participation in the platform does not guarantee an allocation.')],
  ['revenue', 'Revenue for long-term growth', p('Platform revenue supports three priorities: building asset reserves and liquidity, supporting active community projects, and keeping TickerGarden running. The split below applies only to the Platform share of trading fees. Creator, Holder and Staker rewards are unchanged.') + table('How Platform revenue is allocated', ['Allocation', 'Purpose'], [ ['70% · Asset reserves and liquidity', 'Purchase Stock Tokens or real stocks as reserves, and use suitable Stock Tokens to provide liquidity in on-chain pools.'], ['20% · Weekly buyback and burn', 'Select an outstanding community token project each week, buy its tokens on the market and burn the purchased tokens.'], ['10% · Platform operations', 'Support product development, infrastructure, security and day-to-day operations.'] ])],
  ['revenue', '70%: build reserves and liquidity', p('This share is used to purchase Stock Tokens or real stocks as platform reserves. Stock Tokens suitable for on-chain trading can then be supplied to liquidity pools, helping support trading liquidity. Real stocks remain reserve assets and are not deposited directly into on-chain pools.') + p('Fees earned from these liquidity positions will support TickerGarden’s future plans. Further details on their use will be announced as those plans develop. This revenue-funded liquidity is separate from users’ staked Stock and the initial liquidity locked when a community token reaches Bloom.')],
  ['revenue', '20%: support outstanding community projects', p('Each week, TickerGarden selects an eligible project by considering genuine trading activity, social media engagement and community participation. The review looks at the quality and consistency of activity, rather than price gains or trading volume alone.') + p('The weekly buyback budget is used to purchase the selected project’s tokens from the market and burn them, permanently reducing their supply. Selection results, buyback amounts and burn records will be published. If no project qualifies, the budget carries forward to a later week.')],
  ['revenue', '10%: sustain platform operations', p('This share covers the work needed to maintain and develop TickerGarden, including product development, infrastructure, security, audits, compliance and daily operations.')],
  ['revenue', 'What the allocation means for users', p('For every 100 units of base protocol fees, Platform receives 30. Of those 30 units, 21 go toward reserves and liquidity, 6 toward weekly buybacks and burns, and 3 toward operations. These are uses of Platform revenue, not an additional fee or a reward balance users can claim.') + p('Platform reserves do not give community token holders stock ownership, dividends or redemption rights. Providing liquidity carries risk, and buybacks or burns do not guarantee a higher token price.')],
  ['governance', 'Changes to market settings', p('The project can update the assets and settings available for new launches. These changes are subject to governance controls: ordinary changes have a 48-hour delay and reopening paused settings has a 24-hour delay. Some settings can be paused immediately in an emergency.') + p('Existing markets keep their fixed launch terms. Administrative permissions do not give the project ownership of users’ staked Stock or allow it to withdraw locked liquidity principal.')],
  ['governance', 'Transferring creator fee rights', p('The current creator beneficiary can nominate a new wallet, which must accept. Future fees belong to the new beneficiary; previously earned fees remain with their original beneficiary. This transfers fee rights, not token balances or minting control.') + p('This transfer is not currently available through the app. Contact the project through its published support channels for guidance. Both the current and new beneficiary must approve the transfer.')],
  ['network', 'Robinhood Chain mainnet', table('Production network', ['Setting', 'Value'], [ ['Network', 'Robinhood Chain'], ['Chain ID', '4663'], ['Gas asset', 'ETH'], ['Explorer', '<a href="https://robinhoodchain.blockscout.com" target="_blank" rel="noopener noreferrer">Robinhood Chain Explorer ↗</a>'] ]) + p('The addresses below belong to Robinhood Chain mainnet. Before using funds, check that the app and your wallet show the intended network and use the actions available in the app.')],
  ['contracts', 'Mainnet contract addresses', p('Use these mainnet addresses to identify TickerGarden’s core contracts and check activity in the explorer.') + p('For an individual token or market, use the address shown on its market page. Compare addresses rather than names, and use the app’s transaction flow instead of sending assets directly to a contract.')],
  ...productionContracts.map(({ name, address, description }) => ['contracts', name, p(description) + `<a class="docs-contract-address" href="https://robinhoodchain.blockscout.com/address/${address}" target="_blank" rel="noopener noreferrer" aria-label="${name}: ${address} (opens in explorer)">${address}<span aria-hidden="true"> ↗</span></a>`] as const),
  ['risks', 'Contract security and audit status', p('TickerGarden’s contracts have undergone rigorous internal security testing and code review. <strong>They have not yet undergone an independent external audit.</strong> Internal review does not replace independent assessment or eliminate the possibility of defects, exploits or loss of assets.') + p('Only use assets you can afford to lose. Review the network, contract address and every wallet request before signing. Never share your private key or recovery phrase.'), 'risk-contracts'],
  ['risks', 'Trading and liquidity', p('Community tokens can be highly volatile, illiquid or lose all value. Prices can be affected by manipulation, transaction ordering and a lack of buyers. A quote is an estimate; slippage, price impact and network fees affect the final outcome, and failed transactions may still cost gas.') + p('Reaching the Bloom target does not guarantee a successful pool transition. Bloom and permanently locked initial liquidity do not guarantee token value, active trading or the ability to sell at your preferred price. Creating or listing a token is not an endorsement by TickerGarden or the company it references.'), 'risk-trading'],
  ['risks', 'Community tokens, Stock Tokens and real shares', p('A community token created on TickerGarden is not the stock it references. It gives no company ownership, voting rights, dividends, or right to redeem for shares or Stock Tokens. Staked Stock belongs to its depositor and is not a reserve that community token holders can redeem.') + p('A Stock Token is an asset issued by a third party and is not the same as directly holding shares through a brokerage account. Any backing, economic exposure, redemption rights and transfer restrictions depend on the issuer’s terms. Issuer actions, contract changes or underlying-asset events may affect its availability and value; TickerGarden does not guarantee those arrangements.'), 'risk-stock'],
  ['risks', 'Blockchain and third-party services', p('Transactions can be delayed, fail or become irreversible once confirmed. Network congestion, reorganizations and outages may affect trading, staking and claims. Wallets, blockchain access providers, trading infrastructure, token issuers and content services can fail or supply incomplete information.') + p('Displayed prices, balances and statistics may lag behind the chain. USDG is displayed at an assumed value of 1 USD per token; this is a calculation convention, not a guarantee of market price or redemption value. Confirm transaction status before submitting again.'), 'risk-network'],
  ['risks', 'Staking and reward risks', p('Staking rewards depend on actual trading fees and are not guaranteed income. New stake or an addition starts a 24-hour lock for the entire position, including normal claims. An emergency exit forfeits all unclaimed rewards for that position. Contract or underlying-asset failures can put principal at risk.') + p('Holder rewards depend on funded snapshots published by the project. Direct wallet balances are included; LP and indirect holdings are excluded. Publication or claims may be delayed. If token fee burning is enabled, created-token rewards are burned during settlement rather than paid; paired-asset rewards follow the normal rules.') + p('A trade may complete without generating a Staker reward if rewards cannot be recorded. In that case, that trade’s Staker share goes to Platform; previously earned rewards remain recorded. Read the <a href="/terms">Terms of Use</a> before participating.'), 'risk-staking'],
  ['help', 'Contact us', p('Need help or found a problem? Send a direct message to <a href="https://x.com/TickerGarden" target="_blank" rel="noopener noreferrer">@TickerGarden on X</a> or email <a href="mailto:info@tickergarden.com">info@tickergarden.com</a>.') + p('Briefly describe what happened and include the page or market link. For transaction issues, include the transaction hash if available. A screenshot can also help; hide any personal or sensitive information before sending it.')],
  ['help', 'Transaction status and missing data', p('After a launch transaction is sent, the app checks its outcome automatically. Wait for that check before trying again; an unknown result is not the same as a confirmed failure. A wallet approval alone does not finish a trade or stake, and a rejected wallet request does not complete the action. A launch in progress can be restored after refreshing.') + p('Statistics and rewards can lag behind transactions. A dash (-) means missing data, not zero. Never share your recovery phrase or private key with anyone offering support.')],
];

export default {
  title: 'Docs — TickerGarden',
  html: `
<main class="page docs-page">
  <header class="page-hero docs-heading"><div><div class="kicker"><i class="ph ph-book-open-text" aria-hidden="true"></i>Protocol guide</div><h1>Docs</h1></div></header>
  <label class="docs-search"><i class="ph ph-magnifying-glass" aria-hidden="true"></i><input data-docs-search type="search" aria-label="Search docs" placeholder="Search topics, rewards or a contract address" autocomplete="off" /></label>
  <div class="docs-body">
    <nav class="docs-toc" aria-label="Documentation topics"><span class="docs-toc-label">Contents</span>${topics.map(([id, label]) => `<a href="#docs-${id}">${label}<i class="ph ph-arrow-up-right" aria-hidden="true"></i></a>`).join('')}</nav>
    <div class="docs-content">${topics.map(([topic, label], index) => `<section class="docs-section" id="docs-${topic}" data-docs-section aria-labelledby="docs-title-${topic}"><header class="docs-section-heading"><span aria-hidden="true">${String(index + 1).padStart(2, '0')}</span><h2 id="docs-title-${topic}">${label}</h2></header>${articles.filter(([id]) => id === topic).map(([, title, body, id]) => `<article class="docs-article" data-docs-article${id ? ` id="${id}"` : ''}><h3>${title}</h3>${body}</article>`).join('')}</section>`).join('')}
      <p class="docs-empty" data-docs-empty role="status" hidden>No matching articles. Try another search.</p>
    </div>
  </div>
</main>`,
};
