export default {title:'Stats — TickerGarden',html:`
<main class="page stats-page">
<header class="stats-heading"><h1>Stats</h1></header>
<p class="stats-valuation-note">USD estimates use current prices. Volume excludes known internal trades.</p>
<section class="stats-grid" data-stats-summary aria-label="Protocol overview" aria-busy="true">
<article class="stat-card"><div><span>24h volume</span><i class="ph ph-chart-bar" aria-hidden="true"></i></div><strong data-stat-volume>-</strong></article>
<article class="stat-card"><div><span>Token launches in 24h</span><i class="ph ph-plant" aria-hidden="true"></i></div><strong data-stat-launches>-</strong></article>
<article class="stat-card"><div><span>Bloomed markets</span><i class="ph ph-flower" aria-hidden="true"></i></div><strong data-stat-bloomed>-</strong></article>
<article class="stat-card"><div><span>Total staking value</span><i class="ph ph-vault" aria-hidden="true"></i></div><strong data-stat-stock-value title="Allocated Stock valued at current prices">-</strong></article>
<article class="stat-card"><div><span>Staking wallets</span><i class="ph ph-wallet" aria-hidden="true"></i></div><strong data-stat-staking-wallets>-</strong></article>
<article class="stat-card"><div><span>24h fee revenue</span><i class="ph ph-coins" aria-hidden="true"></i></div><strong data-stat-fee-revenue title="Fees generated by trades in 24h, valued at current prices">-</strong></article>
</section>
<section class="stats-secondary-layout">
<article class="stats-panel"><header class="stats-panel-heading"><h2>Staking value by Stock</h2><a class="stats-view-all" href="/stats/stocks">View all <span aria-hidden="true">→</span></a></header><p class="stats-valuation-note">Allocated Stock only. Wallets with an active allocation are counted once.</p><div data-stats-staking-values><p class="stats-empty">-</p></div></article>
<article class="stats-panel"><header class="stats-panel-heading"><h2>Allocated in 24h</h2><span class="stats-unit">USD</span></header><div class="stats-fee-list">
<div class="stats-fee-row"><span>Creator</span><strong data-stat-fee-creator>-</strong></div>
<div class="stats-fee-row"><span>Staker</span><strong data-stat-fee-staker>-</strong></div>
<div class="stats-fee-row"><span>Holder</span><strong data-stat-fee-holder>-</strong></div>
<div class="stats-fee-row"><span>Platform</span><strong data-stat-fee-platform>-</strong></div>
</div></article></section></main>`,};
