export default {title:'Stats — TickerGarden',html:`
<main class="page stats-page">
<header class="stats-heading"><h1>Stats</h1><p><i class="ph ph-clock" aria-hidden="true"></i> Updates Every 20 Minutes</p></header>
<p class="page-status" data-page-status role="status"></p>
<section class="stats-grid" data-stats-summary aria-label="Protocol Overview" aria-busy="true">
<article class="stat-card"><div><span>24H Volume</span><i class="ph ph-chart-bar" aria-hidden="true"></i></div><strong data-stat-volume>-</strong></article>
<article class="stat-card"><div><span>Token Launches In 24H</span><i class="ph ph-plant" aria-hidden="true"></i></div><strong data-stat-launches>-</strong></article>
<article class="stat-card"><div><span>Bloomed Markets</span><i class="ph ph-flower" aria-hidden="true"></i></div><strong data-stat-bloomed>-</strong></article>
<article class="stat-card"><div><span>Total Stock Staked</span><i class="ph ph-vault" aria-hidden="true"></i></div><strong data-stat-stock-value title="Current Testnet Pool Valuation">-</strong></article>
<article class="stat-card"><div><span>Staking Wallets</span><i class="ph ph-wallet" aria-hidden="true"></i></div><strong data-stat-staking-wallets>-</strong></article>
<article class="stat-card"><div><span>24H Fee Revenue</span><i class="ph ph-coins" aria-hidden="true"></i></div><strong data-stat-fee-revenue title="Fees Generated By Trades In 24H, Valued At Current Prices">-</strong></article>
</section>
<section class="stats-secondary-layout">
<article class="stats-panel"><header class="stats-panel-heading"><h2>Stock Staking Value</h2><span class="stats-unit">USD</span></header><div data-stats-staking-values><p class="stats-empty">-</p></div></article>
<article class="stats-panel"><header class="stats-panel-heading"><h2>Allocated In 24H</h2><span class="stats-unit">USD</span></header><div class="stats-fee-list">
<div class="stats-fee-row"><span>Creator</span><strong data-stat-fee-creator>-</strong></div>
<div class="stats-fee-row"><span>Staker</span><strong data-stat-fee-staker>-</strong></div>
<div class="stats-fee-row"><span>Holder</span><strong data-stat-fee-holder>-</strong></div>
<div class="stats-fee-row"><span>Platform</span><strong data-stat-fee-platform>-</strong></div>
</div></article></section></main>`,};
